### ISSUE TITLE
Custom numeric/double NamedMeasurements in test details are broken

### ISSUE THREAD

**Issue by rechenraum** [Kitware/CDash#1017]
Dear all,

In recent docker images, presentation of custom numeric/double NamedMeasurements in a test's detail page seems broken (we have tested the docker images only). The table shows the values of the _first test run always_, no matter what test run is selected. The graphs of respective NamedMeasurements are empty. The standard NamedMeasurements like "Execution Time"/"Test Time" etc. do work however.

Could this issue be related to #989?

Thanks for looking into this!

**Comment by rechenraum** [comment]
Dear all,
Above does not seem to be an issue any more in 3.0.1.
Thanks for you work on cdash!

**Comment by zackgalbreath** [comment]
Thanks for reporting this issue. I'm glad the fix worked for you.
