### ISSUE TITLE
SQL error in SiteInformation

### ISSUE THREAD

**Issue by azukaitis** [Kitware/CDash#1018]
Upon submit I get the following errror:
"SQL error in SiteInformation Insert():SQL error encountered, query hidden.<br><cdash version="2.6.0">"

Any thoughts?

Tony

**Comment by zackgalbreath** [comment]
If you set `APP_ENV=development` in your .env file CDash will log the actual SQL error that it's bumping into. Feel free to share it here.

**Comment by azukaitis** [comment]
I was able to track down the error to and issue where we configure the build on the front end of a cluster, and execute the 'ctest -T Build/Test' on the backend nodes.  The backend node had a different number of CPU's and that was causing the error.  The workaround was a small python script to make the Site attributes consistent among the XML files before submission. Now that I understand the problem I'm hesitant to call this a bug since we are doing things in a non standard manner.
