### ISSUE TITLE
CDash server upgrade when behind firewall

### ISSUE THREAD

**Issue by azukaitis** [Kitware/CDash#1026]
What is the proper way to configure apache/CDash to upgrade thru a proxy?

**Comment by zackgalbreath** [comment]
Generally speaking, you'll want to set the `APP_URL` in your .env file to be CDash's publicly accessible URL.

Off the top of my head, I think that should do it. Are you running into errors during the upgrade process?

**Comment by williamjallen** [comment]
Closing due to no response...
