### ISSUE TITLE
Batch create projects, via API (i.e. curl) or other automation?

### ISSUE THREAD

**Issue by emmenlau** [Kitware/CDash#1057]
Is it possible to create new projects via the API, with CDash v3.0.0? It would be very helpful for large build sites that have hundreds of projects.

We did this successfully with CDash 2.6.0 using curl. However the method was never well developed, because we needed to reverse-engineer the required JSON string. I think this may be because the page for creating projects uses multiple steps? At least with the `View as JSON` link, we get only a partial JSON that is not sufficient to create a new project.

Or are there other means to batch-create projects?

Any help would be greatly appreciated!

**Comment by zackgalbreath** [comment]
If you POST the following data to `/api/v1/project.php` CDash will create a new public project called `MyNewProject` with default config settings.

```
{
   "Submit":true,
   "project":{
      "AuthenticateSubmissions":false,
      "Public":"1",
      "AutoremoveMaxBuilds":500,
      "AutoremoveTimeframe":60,
      "CoverageThreshold":70,
      "EmailBrokenSubmission":1,
      "EmailMaxChars":255,
      "EmailMaxItems":5,
      "NightlyTime":"01:00:00 UTC",
      "ShowCoverageCode":1,
      "TestTimeMaxStatus":3,
      "TestTimeStd":4,
      "TestTimeStdThreshold":1,
      "UploadQuota":1,
      "WarningsFilter":"",
      "ErrorsFilter":"",
      "repositories":[
         {
            "id":0,
            "url":"",
            "branch":"",
            "username":"",
            "password":""
         }
      ],
      "Name":"MyNewProject"
   }
}
```

This won't work without admin access though. Here's instructions on how to generation an authentication token:
https://www.paraview.org/Wiki/CDash:API#Authentication_Token

And here's an example (in python) on how to provide the auth token:
https://github.com/Kitware/CDash/issues/861#issuecomment-499977309

**Comment by emmenlau** [comment]
Closing as fixed with https://github.com/BioDataAnalysis/cdash-client
