### ISSUE TITLE
Project Bug Tracker Issue Creation checkbox not working

### ISSUE THREAD

**Issue by IAL32** [Kitware/CDash#1062]
Version: v3.0.0-rc1-45-gfc1fa3309

The **Bug Tracker Issue Creation** checkbox in the Create/Update project does not set to true neither when creating a project, or when updating it.
But I can indeed add the New Issue URL and the type.

**Comment by zackgalbreath** [comment]
I'm having trouble reproducing this issue. What are you inputting for "Bug Tracker Type" and "New Issue URL"?

**Comment by williamjallen** [comment]
Closing due to lack of response.
