### ISSUE TITLE
Authentication tokens without expiry date do not work in CDash v2.6

### ISSUE THREAD

**Issue by dinkelacker** [Kitware/CDash#1070]
As soon as a valid submission token without expiry date (`$CDASH_TOKEN_DURATION = 0`) is presented, it is deleted from the database. This is because in `app/Model/AuthToken.php:51` the special value `9999-12-31 23:59:59` is inserted for tokens without expiry date. As the maximum value of MySQL's `TIMESTAMP` type is `2038-01-19 03:14:07` however, it is implicitly inserted as `0000-00-00 00:00:00` and as soon as it is compared to the current date, it is deleted by mistake.

**Comment by zackgalbreath** [comment]
Thanks for letting us know!
