### ISSUE TITLE
3.0.1 Base install failure

### ISSUE THREAD

**Issue by jonathan-dove** [Kitware/CDash#1078]
Tried to do just a base install in Debian Stretch with the following specs:
PHP 7.4.10
NPM 6.14.8
Composer 1.10.13

When I do follow the base instructions for installation I get a 404 error that it can't find install.php... it is able to hit index.php obviously.
after a ton of different ways of attacking this, I tried installing 2.6, got to install.php, created a single project to create the database... all of that worked just fine. 
Then I reinstalled 3.0.3 and got the dashboard, but can't get to any other page. I get 404 errors for every page I go to from the front page (user.php, ViewProjects.php, ect...)

**Comment by zackgalbreath** [comment]
This is just a hunch, but it sounds like your web server isn't honoring the RewriteRules used for routing that are defined in CDash's `.htaccess` file.

Are you using apache or nginx as your web server?

**Comment by jonathan-dove** [comment]
apache

**Comment by zackgalbreath** [comment]
In that case, check that you have `AllowOverride All` set in the apache configuration for the relevant VirtualHost or Directory.

A way to test if this is working or not is to add the following snippet to the top CDash's public/.htaccess file:

```
Authtype Basic
AuthName "My custom CDash test auth"
AuthUserFile /var/www/htpasswd
Require valid-user
```

If apache is configured to parse .htacess files then you should be presented with an authentication dialog when you browse to any CDash URL.

**Comment by lockywolf** [comment]
I am using nginx, and my URLs seem to be wrong (all least a part of them).

So, I am running CDash in docker, APP_URL is `http://my.server/cdash/` (with the trailing slash), 
and nginx.conf has
```
       location /cdash/ # with slash
        {
                proxy_pass http://server.yuwei:3001/; # with slash but not adding the suffix
```

And I can access "some" resources, but not others.

**Comment by williamjallen** [comment]
The installation process has been completely overhauled since this issue was posted.  If you continue to have issues with the latest version of CDash, please open a new issue.
