### ISSUE TITLE
Delete a project

### ISSUE THREAD

**Issue by bobby-philip** [Kitware/CDash#1081]
Hi:

How do I delete a project in CDash? I'm using CDash 3.0.1

**Comment by zackgalbreath** [comment]
1. Log in as a project admin.
2. On your project dashboard (index.php), towards the top of the screen, hover over the Settings menu and click Project.
3. Navigate to the Miscellaneous tab.
4. Click the "Delete Project" button.

**Comment by fperignon** [comment]
Hi, 

maybe I missed something but when I try to delete a project (project -> misc -> delete), it does not disappear from my dashboard. Is it normal ? 

Thank you

**Comment by williamjallen** [comment]
This appears to be working on the latest version of CDash.
