### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by LLlKuIIeP** [Kitware/CDash#1085]
Good afternoon.

Can you please tell me, can you send CDash, for example, a WebHook when you receive an assembly? I really want to receive notifications in case of an unsuccessful build of the application.

Thanks.

**Comment by zackgalbreath** [comment]
CDash does have support for notifications, but this has only ever really been used to send emails when something goes wrong. This can be set on a per-project, per-buildgroup, and/or per-user level.

**Comment by LLlKuIIeP** [comment]
Thank you.
