### ISSUE TITLE
cannot delete dynamic groups without site

### ISSUE THREAD

**Issue by utkarshayachit** [Kitware/CDash#1092]
On ParaView dashoard, for some reason we now have entries in the dyamic groups that don't have "site" strings present. And those can no longer be deleted. Hitting the delete button next to it has no effect.

![image](https://user-images.githubusercontent.com/97864/98854608-c659d580-2428-11eb-95c3-d33f0d1878c3.png)

**Comment by zackgalbreath** [comment]
Thanks for letting me know. This should be fixed now. I didn't want to test deleting any rows, so I left that up to you.

**Comment by utkarshayachit** [comment]
thanks a bunch for the quick fix. works as expected!
