### ISSUE TITLE
Dynamic Analysis log (compressed output) reported on CDash v3.0.1 is not complete (even when it is not truncated)

### ISSUE THREAD

**Issue by cfriebel** [Kitware/CDash#1097]
It seems that, since buffers are used when decompressing dynamic analysis logs, only the last chunk (with size <1024) is stored in the database and reported on the dashboard, even though the maximum size of the log (i.e. 1024x1024) is not reached.

This can be reproduced with the attached _hello world_ program ([main.zip](https://github.com/Kitware/CDash/files/5591419/main.zip)) in which (enough) leaks are introduced on purpose.

To me there is a bug in app/cdash/app/Model/DynamicAnalysis.php at line 165. The statement (assignment)
`$uncompressed_log = inflate_add($inflate_context, $chunk, ZLIB_NO_FLUSH);` should be changed into (concatenation assignment)
`$uncompressed_log .= inflate_add($inflate_context, $chunk, ZLIB_NO_FLUSH);`

At least, this change fixed the problem for the _hello world_ program in attachment.

Remark: the problem does not occur when the output in not compressed (e.g. ctest --no-compress-output).

CMake/CTest version: 3.11.4
CDash version: 3.0.1
Valgrind version: 3.15.0
Valgrind options: --tool=memcheck --leak-check=full --show-reachable=yes --track-origins=yes"

**Comment by emmenlau** [comment]
I'm also affected by this, or at least I suspect this is the case when having large logs.

**Comment by zackgalbreath** [comment]
Thanks for reporting this and providing a reproducer!

This is fixed in #1109
