### ISSUE TITLE
Closed network systems

### ISSUE THREAD

**Issue by azukaitis** [Kitware/CDash#1100]
New to the Docker capability.  My question is how would I update a the version of CDash in the Docker container instantiated on a closed network ( Need to do it off of a USB stick ) ?

Would I need to create a new container with the new version and transfer the SQL database from the old container to the new? I'd imagine this would break at some point if the database format ever changed.

Thanks!
Tony

**Comment by zackgalbreath** [comment]
Our docker-compose system creates separate containers for the database and the web server. So you could probably get away with recreating the web server as-is, and then using it to update the database whenever the schema changes. At the very least, this would save you from having to manually migrate the database each time you do an upgrade.
