### ISSUE TITLE
Experimental CTest results not showing anymore since January

### ISSUE THREAD

**Issue by ViktorvdValk** [Kitware/CDash#1116]
On the 29th of december, the ctest results were showing on my.cdash.org dashboard under an experimental tab, but the experimental ctests from +/- the past 1.5 months are not visible anymore.

The ctests are run in a GA workflow using:         
`ctest -M Experimental -T Test -C Release -VV -j 2`

and were supposed to be uploaded to the elastix project on my.cdash.org.

Did anything change is after the 29th of december or what could be the reason for this?
The script did not change and running the exact same script in the repo as it was on the 29th of december, doesn't result in any output on my.cdash.

**Comment by zackgalbreath** [comment]
Thanks for letting us know. I'll poke around a bit on the server for clues & report back here.

**Comment by zackgalbreath** [comment]
It looks like you're missing a `-T Submit` argument to tell CTest to upload the XML results to CDash.

I cloned elastix to experiment with this locally. This command:

```ctest -M Experimental -T Configure -C Release -VV -j 2```
...resulted in no builds getting created on CDash.

But doing this:

```ctest -M Experimental -T Configure -T Submit -C Release -VV -j 2```
created the following build:
https://my.cdash.org/build/1969270

**Comment by ViktorvdValk** [comment]
Yes, the results are indeed uploaded now, thanks a lot!
