### ISSUE TITLE
Links to subprojects are incorrect

### ISSUE THREAD

**Issue by jhux2** [Kitware/CDash#1122]
In the Trilinos project dashboard, the links to subprojects are incorrect, as can be seen here:  https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=MueLu.  At the top of the page are links to Subproject Dependencies that have the form http://testing.sandia.gov/cdash/index.php?subproject=<some_package>&.  It seems that those links should instead be http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=<some_package>.

I originally posted this issue at https://github.com/trilinos/Trilinos/issues/1270, but @bartlettroscoe suggested posting it here instead, as it may be a defect in cdash.

Please let me know if I can provide more information, thank you.

**Comment by zackgalbreath** [comment]
You're right, that's a bug. Thanks for bringing this to our attention.

**Comment by zackgalbreath** [comment]
Fixed in #1131
