### ISSUE TITLE
`kitware_logo_footer.png` is too low resolution, and blurry looking

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#1128]
`kitware_logo_footer.png` is 3 kB and 101 x 26 pixels.  At the scaling factor I use in my web browser, it looks noticeably blurry.  I don't even have a HiDPI monitor either.

Contrast with `cdash.png` at 19 kB and 270 x 270 pixels, which looks quite nice.

**Comment by seanm** [comment]
Actually, this is a regression vs cdash 2.6, which has a bigger `kitware_logo.png` at 1421 x 365 pixels.

**Comment by williamjallen** [comment]
This appears to have been fixed sometime since this issue was created.  Ultimately it would be better to use a SVG image in the footer, but the current PNG seems to have a high enough resolution that it isn't particularly blurry, even on my high-resolution display.
