### ISSUE TITLE
No tags for v3.0.{1,2,3} on Docker hub

### ISSUE THREAD

**Issue by estan** [Kitware/CDash#1156]
It seems there is only a tag for `v3.0.0` and the floating `latest` tag (?).

**Comment by zackgalbreath** [comment]
Whoops, you're right. We'll have to make this a more automated part of our release process. In the meantime, I just pushed a [tag for v3.0.3](https://hub.docker.com/r/kitware/cdash/tags).

**Comment by estan** [comment]
Thanks @zackgalbreath
