### ISSUE TITLE
"Cannot connect to cdash on localhost using login root."

### ISSUE THREAD

**Issue by clement-analogue** [Kitware/CDash#1167]
Hi,

I'm trying to install CDash on Ubuntu 20.04 with Apache and MySQL. All dependencies are installed using apt.

At the end of installation process, on the page http://localhost/install.php, the first line is
`$CDASH_DB_PASS = 'test'; $CDASH_BASE_URL="http://localhost" $CDASH_USE_HTTPS=0 $CDASH_DB_PASS = 'test'; $CDASH_BASE_URL="http://localhost" $CDASH_USE_HTTPS=0 `

Then, I have the following error
```
Please follow the installation step to make sure your system meets the requirements.

Cannot connect to cdash on localhost using login root.
Make sure you have modified the settings in the config.php file.
```
See screenshot bellow.

`% mysql -h localhost -uroot -ptest cdash` works fine.

What can be the issue?

Note, I couldn't find session and zlib modules for php. There are no php-session not php-zlib packages.

![Screenshot from 2021-08-01 15-46-44](https://user-images.githubusercontent.com/1931507/127773190-277de350-b23a-4d20-94be-189f667042a3.png)

**Comment by williamjallen** [comment]
Closing this issue since `install.php` has been gone for a while.  Please open a new issue if you continue to experience problems with a recent version of CDash.
