### ISSUE TITLE
Unable to complete CDash installation

### ISSUE THREAD

**Issue by darkjedi521** [Kitware/CDash#1187]
While following the instructions here: https://github.com/Kitware/CDash/blob/master/docs/install.md on both Ubnutu 20.04 LTS server and FreeBSD 13.0, the installation fails at the final step.  When I attempt to load http://servername, I get a redirect to http://localhost/install.php.  Running curl against the server gave me the following output:
```
$CDASH_DB_LOGIN = 'cdash';
$CDASH_DB_PASS = 'LIKE_I_WOULD_POST_IT_IN_PUBLIC';
$CDASH_BASE_URL = 'http://cdash.domain.tld/';
$CDASH_USE_HTTPS = '0';
$CDASH_CURL_REQUEST_LOCALHOST = '0';
$CDASH_SERVER_NAME = 'cdash.domain.tld';
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='http://localhost/install.php'" />

        <title>Redirecting to http://localhost/install.php</title>
    </head>
    <body>
        Redirecting to <a href="http://localhost/install.php">http://localhost/install.php</a>.
    </body>
```
Running php /opt/CDash/public/index.php on the server gives the same output.

**Comment by zackgalbreath** [comment]
You have `APP_URL` defined in your .env file, and then you have this line later on in that same file, right?

```
MIX_APP_URL="${APP_URL}"
```

> I get a text document with the CDASH variables in it instead.

This behavior isn't ringing a bell to me, unfortunately. Here's a quick test to see if your web server is rendering PHP scripts correctly. Try writing a file to `CDash/public/phpinfo.php` with the following contents:


```php
<?php
phpinfo();
```

Next open `http://cdash.domain.tld/phpinfo.php` with a web browser to see if it renders correctly or not.

**Comment by williamjallen** [comment]
Closing this issue since it has been open for a while with no response.  Please comment here or open a new issue if you continue to experience problems with the latest version of CDash.
