### ISSUE TITLE
Problem when too many subprojects in CMAKE_LABELS_FOR_SUBPROJECTS

### ISSUE THREAD

**Issue by rhauser** [Kitware/CDash#1189]
This is a problem seen with cdash v2.6 and v3.0.3. 

We recently tried to enable the all-at-once subproject feature in our project. This is a large code base with one top level git repo and about 200 submodules.  In CTestConfig.cmake we set CMAKE_LABELS_FOR_SUBPROJECTS  to the list of all submodules (all the sub directory are also labelled correctly). 

This seems to work only up to a certain number of subprojects - a bit over 100 (haven't it bisected down to the last one).
I can reduce the number of items in CMAKE_LABELS_FOR_SUBPROJECTS to less than 100 and then it works (but lumps all the rest together, of course). Subprojects are created automatically etc. 

The update submission works (we upload results partially), configure/build/test all fail and don't show up

The two installations are running on a custom kubernetes cluster with no explicit memory limit (v2.6) and an openshift/okd 4 cluster (v3.0.3) but the behaviour is almost the same. Memory consumption is about 300MB. The image is based on the upstream kitware docker image.

Below is a typical log output when e.g. the Configure.xml is submitted:

```
[2021-11-09 18:59:58] development.ERROR: error: could not create handler based on xml content {"function":"ctest_parse"}
10.76.16.1 - - [09/Nov/2021:18:59:58 +0000] "PUT /submit.php?project=tdaq&FileName=rhauser-inspiron___tdaq-99-00-00-x86_64-centos7-gcc11-opt___20211109-1859-Experimental___XML___Configure.xml&build=tdaq-99-00-00-x86_64-centos7-gcc11-opt&site=rhauser-inspiron&stamp=20211109-1859-Experimental&MD5=4e1fef8fcdda3663d202c2a48bc6ceee HTTP/1.1" 200 1121
```
Any ideas, or advice to get more info that helps ?

**Comment by rhauser** [comment]
The underlying issue is  that the ctest_parse() function tries to determine the xml handler from the first 8192 bytes of the submission. If there is a large number of subprojects this fails, since they appear before the tags that are checked for.

The hack in https://github.com/rhauser/CDash/commit/c14299c28b01a794e340660b06c6a9765393be57 is just to show that it makes our use case work, but is no general solution.

**Comment by zackgalbreath** [comment]
Thanks for bringing this to our attention, and for digging into the underlying cause.

If it's not too much trouble, could you share an offending XML file with us so we can play around with it more locally?

**Comment by rhauser** [comment]
[Configure.xml.zip](https://github.com/Kitware/CDash/files/7563631/Configure.xml.zip)

Sure, here is an example.
