### ISSUE TITLE
Filtering tests by label seems to include extra tests that shouldn't match

### ISSUE THREAD

**Issue by craigscott-crascit** [Kitware/CDash#1191]
I was looking at how CDash allows you to filter a test query by label. I thought I'd check what CMake's own dashboard results show when I add a filter that only includes tests whose label includes `Qt`, since I know a relatively small number of tests have that in their labels (some will have `Qt5` or `Qt6`). I was surprised when other tests that do not have any labels with `Qt` assigned to them were also included in the results. As an example, take a look at the following query (give it time, it takes ages for it to load the page now that there are so many sites submitting for the CMake project):

https://open.cdash.org/queryTests.php?project=CMake&date=2021-11-13&filtercount=1&showfilters=1&field1=label&compare1=63&value1=Qt

To pick a random case, the FindALSA.Test case shouldn't have any labels that match, yet it appears in the results. Unfortunately, because the output of passing tests is truncated fairly severely, we can't see the full output to confirm that there is no `<CTestLabel>...</CTestLabel>` tag pair adding custom labels dynamically (a new feature in CMake 3.22, which I'm checking and why I'm even looking at this area). That test case has no `LABELS` set as test properties at configure time.

CC: @bradking @mathstuf I doubt this is caused by the new functionality added in CMake 3.22, but keeping you in loop since this bug limits the usefulness of that new feature.

**Comment by zackgalbreath** [comment]
I think you're right, this is a legitimate bug. Thanks for bringing it to our attention.

**Comment by zackgalbreath** [comment]
I applied the patch from #1192 to open.cdash.org and it seems to be doing the right thing now:

https://open.cdash.org/queryTests.php?project=CMake&date=2021-11-13&filtercount=1&showfilters=1&field1=label&compare1=63&value1=Qt
