### ISSUE TITLE
Using mysql backend does not support submitting results from systems with 256 or more logical cpus

### ISSUE THREAD

**Issue by msimberg** [Kitware/CDash#1196]
Systems like a 2x64 cores EPYC with hyperthreading have 256 logical cpus. Submitting results from such a system leads to SQL errors such as `SQL error in SiteInformation Insert():Out of range value for column 'numberlogicalcpus' at row 1<br><cdash version="2.7.0">` because `numberlogicalcpus` is stored in a `tinyint` (https://github.com/Kitware/CDash/blob/00662bad554e6842d1a7282f29e7bc1f221688ea/app/cdash/sql/mysql/cdash.sql#L494).

Would it be possible to update that to a bigger field? I suppose the `numberphysicalcpus` should also be able to store larger numbers.

**Comment by zackgalbreath** [comment]
fixed by #1199
