### ISSUE TITLE
CDash shows wrong version after upgrade, or am I missing an upgrade step?

### ISSUE THREAD

**Issue by emmenlau** [Kitware/CDash#1198]
I've installed CDash 3.0.0 originally, then upgraded to 3.0.2, and finally to 3.0.3. With `git status` I see `HEAD detached at v3.0.3` which seems correct. However on the bottom right of every page, CDash reports `CDash v3.0.0-rc1-45-gfc1fa3309`.

What version is that? Is is the version of the database? Am I missing an upgrade step of the database?

**Comment by emmenlau** [comment]
Aha, I was missing the call to `npm run dev`. Closing as fixed.

**Comment by seanm** [comment]
We just updated from 3.2.0-rc1 to 3.2.3 and also noticed the version on the page footer was not updated. It turned out to be the file `public/VERSION` that was not updated.

**Comment by williamjallen** [comment]
@seanm You need to run `npm run prod` to regenerate `public/VERSION` and build the frontend as part of the upgrade process.  Did you run all of the commands in `install.sh`?

**Comment by seanm** [comment]
> @seanm You need to run `npm run prod` to regenerate `public/VERSION`

We indeed ran `npm run production`, hopefully that's the same?

>and build the frontend as part of the upgrade process. Did you run all of the commands in `install.sh`?

There's an `install.sh`?  We followed https://github.com/Kitware/CDash/blob/master/docs/install.md. Is that what you meant?

**Comment by williamjallen** [comment]
> We indeed ran `npm run production`, hopefully that's the same?

Yes, `npm run prod` and `npm run production` run the same script.

> There's an `install.sh`? We followed https://github.com/Kitware/CDash/blob/master/docs/install.md. Is that what you meant?

Recent versions of CDash have an [`install.sh`](https://github.com/Kitware/CDash/blob/master/install.sh) script which runs both the required and optional installation commands.  For CDash 3.2, running `npm run production` is all that's needed.  Was `public/VERSION` incorrect after you ran `npm run production`?

**Comment by seanm** [comment]
Today we updated from 3.2.3 to 3.4.2 and again the version at the bottom is incorrect, it shows v3.4.0, and indeed the file in `CDash/public/VERSION` contains `v3.4.0`.

We didn't use `install.sh` though, because we'd done our testing without it.
