### ISSUE TITLE
Support npm v8

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#1219]
install.md currently says:

Before installing CDash, you will need:

-    A web server: [Apache](https://httpd.apache.org/) or [NGINX](https://www.nginx.com/)
-    A database: [MySQL v5.x+](https://www.mysql.com/) or [PostgreSQL v9.2+](https://www.postgresql.org/)
-    [PHP 7.3+](https://www.php.net/)
-    [Composer v2.x](https://getcomposer.org/) (to install PHP dependencies)
-    [npm v6](https://www.npmjs.com/) (to install Javascript dependencies)

The lack of a `+` character on `npm v6` suggests than npm v8 is not supported.  Is that so?

**Comment by williamjallen** [comment]
The latest Docker image comes with NPM 9.x, but any recent version of NPM should work.
