### ISSUE TITLE
Unable to create a new project (cdash.org)

### ISSUE THREAD

**Issue by sedwinj** [Kitware/CDash#1220]
_(I'm new to the service, so please forgive any ignorance on my part.)_

### Problem:
When clicking the "Create Project>>" button in the project creation wizard on cdash.org, nothing happens.

### Expected outcome:
A new project is created, and some sort of confirmation is displayed,
OR, an error is displayed indicating why the project could not be created.

### Steps to recreate:
Navigate to https://my.cdash.org/project/new , fill in the "Name:" field, then advance to the "Miscellaneous" tab and press the "Create Project>>" button.

This issue was tested and is present on the following web browsers: Brave (chromium), Microsoft Edge, Safari (iOS).

**Comment by zackgalbreath** [comment]
I'm having trouble reproducing this one. What was the name of the project you attempted to create?
