### ISSUE TITLE
Submissions not visible on Nalu-Wind dashboard

### ISSUE THREAD

**Issue by tasmith4** [Kitware/CDash#1229]
I'm trying to set up a new machine here at Sandia to run nightly tests for the Nalu-Wind project.  After running our ctest script, the output reports successful submission, but the results are not reliably visible on the CDash page (https://my.cdash.org/index.php?project=Nalu-Wind) -- they have only showed up a couple days out of the 2-3 weeks I've been running nightly.

I found #914 where a similar issue seemed to be caused by an outdated version of CMake -- I'm seeing this problem with both 3.20.0 and 3.22.2, which I thought were fairly recent ... has a more recent change broken backwards compatibility for dashboard submission?

Can you give guidance on what further things to check to debug this issue?  A recent set of submission output follows:

```
 -- Submit - LinuxTest --
SetCTestConfiguration:BuildDirectory:/scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests
SetCTestConfiguration:SourceDirectory:/scratch/tasmit/exawind-spin/source/nalu-wind
SetCTestConfigurationFromCMakeVariable:DropMethod:CTEST_DROP_METHOD
SetCTestConfiguration:DropMethod:http
SetCTestConfigurationFromCMakeVariable:DropSite:CTEST_DROP_SITE
SetCTestConfiguration:DropSite:my.cdash.org
SetCTestConfigurationFromCMakeVariable:DropLocation:CTEST_DROP_LOCATION
SetCTestConfiguration:DropLocation:/submit.php?project=Nalu-Wind
Submit files
   Send to group: Nightly
   SubmitURL: http://my.cdash.org/submit.php?project=Nalu-Wind
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Update.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Update.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=95901e33dcfc85f6b653afa69182901f Size: 613
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Update.xml
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Configure.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Configure.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=871196f3666bf20dc5134ba19d35d3ee Size: 4155
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Configure.xml
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Build.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Build.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=0291332518c268df39aba92ea0e484b6 Size: 38305
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Build.xml
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Test.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Test.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=b4e8d0157bc9e05c505dd2403a117ab4 Size: 32587
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Test.xml
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Notes.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Notes.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=45d51b2206e4cfcb81d6afd5dd80746f Size: 284
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Notes.xml
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Done.xml to http://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220322-0400-Nightly___XML___Done.xml&build=LinuxTest&site=ascicgpu057&stamp=20220322-0400-Nightly&MD5=7fb9796641f5ac2651c6b6d37e9d91c5 Size: 100
   Uploaded: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220322-0400/Done.xml
   Submission successful
 -- Submit exit code = 0 --

 -- Finished - LinuxTest --
```

**Comment by zackgalbreath** [comment]
I'm not seeing any good hints in the logs on the web server either, unfortunately.

Would you please try submitting over https (instead of http) to see if that helps?

**Comment by tasmith4** [comment]
@zackgalbreath sure.  Just curious, do the files actually show up on the server, and aren't displayed, or do they not show up at all?

**Comment by zackgalbreath** [comment]
> @zackgalbreath sure. Just curious, do the files actually show up on the server, and aren't displayed, or do they not show up at all?

I did not see the files in the backup directory on the web server, nor did I see any mention of them in our Apache access/error logs.

FWIW, my.cdash.org does accept submissions over both http and https (I just tested this) so it's possible that Sandia's proxy is getting in the way.

**Comment by tasmith4** [comment]
Ok I suspected the proxy but was thought that if that was the issue CTest would not report "Submission successful"

**Comment by zackgalbreath** [comment]
> Ok I suspected the proxy but was thought that if that was the issue CTest would not report "Submission successful"

Agreed, that message is really misleading if it turns out to be a proxy issue.

**Comment by tasmith4** [comment]
So I tried submitting with https by putting `set(CTEST_SUBMIT_URL "https://my.cdash.org/submit.php?project=Nalu-Wind")` in my ctest script.

Now it's still failing, but failing differently:
```
 -- Submit - LinuxTest --
SetCTestConfiguration:BuildDirectory:/scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests
SetCTestConfiguration:SourceDirectory:/scratch/tasmit/exawind-spin/source/nalu-wind
SetCTestConfiguration:SubmitURL:https://my.cdash.org/submit.php?project=Nalu-Wind
Submit files
   Send to group: Nightly
   SubmitURL: https://my.cdash.org/submit.php?project=Nalu-Wind
   Upload file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220323-0400/Update.xml to https://my.cdash.org/submit.php?project=Nalu-Wind&FileName=ascicgpu057___LinuxTest___20220323-0400-Nightly___XML___Update.xml&build=LinuxTest&site=ascicgpu057&stamp=20220323-0400-Nightly&MD5=71147df1d6be075c76b5ee7573ccd625 Size: 613
   Submit failed, waiting 20 seconds...
   Retry submission: Attempt 1 of 20
# several more just like this ...
   Submit failed, waiting 20 seconds...
   Retry submission: Attempt 20 of 20
   Error when uploading file: /scratch/tasmit/exawind-spin/source/nalu-wind/builds/release-tests/Testing/20220323-0400/Update.xml
   Error message was: Protocol "https" not supported or disabled in libcurl
   Problems when submitting via HTTP
 -- Submit exit code = -1 --

 -- Finished - LinuxTest --
```

**Comment by tasmith4** [comment]
@zackgalbreath I was able to find a different machine on Sandia's network that can successfully submit.  So it must be some machine-specific issue, which I'll pursue further with Sandia IT staff.  Thanks for taking the time to check things out on the cdash side!

**Comment by tasmith4** [comment]
@zackgalbreath follow-up question, since Sandia IT and I are still having trouble tracking this down:  Are there any filters on my.cdash.org that would prevent a file from being copied to the server and/or displayed on the dashboard?  (i.e. perhaps some xml issue or size limit or something is blocking my files from showing up)

Alternatively, are there any type of user account restrictions that could be keeping some of my submissions from going through?

**Comment by tasmith4** [comment]
@zackgalbreath bumping this, since I'd like to rule out a couple more things on the CDash side as noted in my comment above.

**Comment by zackgalbreath** [comment]
Sorry for the slow reply. I don't think you're running afoul of any server-side filtering on cdash.org. I don't see any mention of `ascicgpu057` in Apache's access or error logs. I do happen to have SRN access. Let me know if I can help you get this working from the client side.

**Comment by tasmith4** [comment]
@zackgalbreath yeah that would be great.  One thing I was struggling with is getting a minimal reproducer that doesn't involve building the whole project every time, maybe you have some ideas there?  I do have a build with the xml files in it, but I don't know how to try the submission process outside of the ctest script that builds the whole code.  My Sandia email is tasmit, if it's easier to communicate directly.

**Comment by tasmith4** [comment]
Thanks for all your help @zackgalbreath!
