### ISSUE TITLE
Docker Compose : installation database issues and undefined links

### ISSUE THREAD

**Issue by salomon-chung** [Kitware/CDash#1270]
Hello,

I tried to install CDash on Linux following
https://github.com/Kitware/CDash/blob/master/docs/docker.md.

*Installation*

However I encountered some issues:

```bash
$ docker compose run --rm cdash install configure
[...]
In Connection.php line 669:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cdash.user' doesn't exist (SQL: select * from `user` where `email` = remove.this.user@example.org limit 1)
[...]
```

2 issues may have similar messages:

- https://github.com/Kitware/CDash/issues/1054
- https://github.com/Kitware/CDash/issues/780

Here is the patch I used as a workaround:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index c6d77bf91..5f6befa7e 120000
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1 +1 @@
-docker/docker-compose.production.yml
\ No newline at end of file
+docker/docker-compose.mysql.yml
\ No newline at end of file
diff --git a/docker/docker-compose.mysql.yml b/docker/docker-compose.mysql.yml
[...]
diff --git a/docker/docker-entrypoint.sh b/docker/docker-entrypoint.sh
index 5d6a8cad2..dfbc58ec1 100755
--- a/docker/docker-entrypoint.sh
+++ b/docker/docker-entrypoint.sh
@@ -532,5 +532,7 @@ if [ "$do_serve" '!=' '1' ] ; then
     exit
 fi
 
+chown -R www-data:www-data /home/kitware/cdash
+
 # serve
 exec /usr/sbin/apache2ctl -D FOREGROUND
```

Can you give a better solution?

*Links*

For a build on CDash, "View [...] Summary" links are broken:
```
Not found
```

For instance CDash shows link to :

`http://[...]:[...]/build/undefined/build/54/configure`

But the correct URL seems to be:

`http://[...]:[...]/build/54/configure`

How can I solve this issue ?

Best regards,

Salomon CHUNG

**Comment by rchocat** [comment]
Hi, 

Is it possible to answer if we can solve the issue exposed by Salomon ?

Thanks

Greats

Rudy

**Comment by williamjallen** [comment]
@salomon-chung We have revamped our Docker deployment support significantly since this issue was posted.  Please feel free to re-open this issue if you are still experiencing the problem with the latest version of master.
