### ISSUE TITLE
Calendar UI overlaps with other content

### ISSUE THREAD

**Issue by williamjallen** [Kitware/CDash#1306]
The calendar menu item overlaps with the rest of the page content, which makes it almost unusable.  See image below:

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/16820599/221388833-7442c462-a9ac-40b6-9a5c-46f2e2d7facb.png">

**Comment by zackgalbreath** [comment]
Thanks for noticing this. This is a regression from CDash v3.1.0. I'll try to track it down & fix it.
