### ISSUE TITLE
`kitware/cdash_common` does not exist

### ISSUE THREAD

**Issue by sykhro** [Kitware/CDash#1311]
As per title, the Docker image `kitware/cdash_common` does not exist or isn't public on DockerHub. Therefore the `docker-compose` setup is broken out of the box.

**Comment by josephsnyder** [comment]
@sykhro, thanks for the report.  I am responsible for adding that and also for the documentation update that needed to follow it more quickly than it has: https://github.com/Kitware/CDash/pull/1310/files

If you use `docker-compose pull` before the `up` command, the images will be available.

**Comment by sykhro** [comment]
> @sykhro, thanks for the report. I am responsible for adding that and also for the documentation update that needed to follow it more quickly than it has: https://github.com/Kitware/CDash/pull/1310/files
> 
> If you use `docker-compose pull` before the `up` command, the images will be available.

Thank you for the quick response, I saw the PR shortly after opening this issue. I'll leave this here in case anyone else misses the PR until it's merged
