### ISSUE TITLE
Consider adding padding to viewTest.php table

### ISSUE THREAD

**Issue by zachmullen** [Kitware/CDash#133]
I think it would increase readability. See screenshot.

![screen shot 2015-10-27 at 10 00 01 am](https://cloud.githubusercontent.com/assets/555959/10760187/af1ddc0c-7c91-11e5-992a-9647d26322ce.png)

**Comment by zackgalbreath** [comment]
Thanks for pointing this out.  e14877b adds padding to the tables on viewTest and testSummary.
