### ISSUE TITLE
'Not found' when opening links from Project > Settings

### ISSUE THREAD

**Issue by willfern123** [Kitware/CDash#1385]
Hi,

When clicking on most links from the Project Settings page such as attempting to download the CTestConfig.cmake, returning to my dashboard with the top-right button, or clicking on 'My CDash' in the top-left:

![image](https://user-images.githubusercontent.com/130184717/234354840-813f1f38-6771-4586-834f-9f262c13684b.png)

An empty webpage with 'Not found' appears. I've manually written my own CTestConfig.cmake, though, but I'd like to see how/what the CTestConfig.cmake generates.

**Comment by williamjallen** [comment]
I believe that this is fixed by https://github.com/Kitware/CDash/pull/1351
