### ISSUE TITLE
CDash install fails due to incorrect database being accessed with PostgreSQL

### ISSUE THREAD

**Issue by ngladitz** [Kitware/CDash#143]
The pdo_select_db("") line here:
https://github.com/Kitware/CDash/blob/301cb0405e40335e33002cb77378a744d00fcfbc/install.php#L114

Causes CDash to access the user's default database [1].
If no such database exists this fails.

See also:
http://public.kitware.com/pipermail/cdash/2015-October/001664.html

[1] http://www.postgresql.org/docs/9.2/static/libpq-connect.html#LIBPQ-CONNECT-DBNAME

**Comment by zackgalbreath** [comment]
Thanks for tracking this down.  When you get a chance, please test out #149 and let me know if it works for you.

**Comment by ngladitz** [comment]
Thanks, that seems to fix the issue for me.

**Comment by zackgalbreath** [comment]
Fixed via #149.
