### ISSUE TITLE
MAIL_FROM_NAME is not used

### ISSUE THREAD

**Issue by sjoubert** [Kitware/CDash#1476]
# Bug report

### Expected Behavior

Providing a value (or even the default value) to the MAIL_FROM_NAME env variable should impact the sent email.

### Actual Behavior

No name is set on the sent email, not even the default `CDash` value

### CDash Version

v3.1.0

**Comment by williamjallen** [comment]
Closed by https://github.com/Kitware/CDash/pull/1530.
