### ISSUE TITLE
MAIL_REPLY_* variable are not used

### ISSUE THREAD

**Issue by sjoubert** [Kitware/CDash#1477]
# Bug report

### Actual Behavior

Not sure if this is actually a bug or a behavior modification but the MAIL_REPLY_ADDRESS env variable is not used anymore.
The `mail.reply_to` config entries (address and name) are now initialized using the `MAIL_FROM` variables.

Note: similar to #1476 the mail.reply_to.name config entry is not used in the actual email.

### Expected Behavior

Either use the `MAIL_REPLY` variables or remove any mention of them and document the use of `MAIL_FROM` instead.

### CDash Version

v3.1.0/master

**Comment by williamjallen** [comment]
Closed by https://github.com/Kitware/CDash/pull/1530.
