### ISSUE TITLE
The current database schema doesn't match the version of CDash you are running, upgrade your database structure in the Administration/CDash maintenance panel of CDash 

### ISSUE THREAD

**Issue by stephenvillagonzalo** [Kitware/CDash#1488]
# Bug report

### Expected Behavior

Program should run correctly

### Actual Behavior

The current database schema doesn't match the version of CDash you are running, upgrade your database structure in the [Administration/CDash maintenance panel of CDash](http://stephen-cdash-t01.test.oakland.edu/upgrade.php)

### CDash Version

3.1.0

### Additional Information

Add additional information here if necessary.  Helpful information includes:
- How to reproduce the problem
   Rhel 8.7, https, mysql 8.0 (tried also mariadb 10.3), php 7.4 and all modules needed, nodejs12 , composer 2.5.8, npm 6.14.16
- Screenshots of a UI issue
- 
<img width="679" alt="image" src="https://github.com/Kitware/CDash/assets/79467722/4e54852c-700f-433f-938c-8e8adc8c4f02">

- Browser/OS information (if applicable)
- Firefox 114. safari 16.4
- Any other information which might help us track down the bug
- clean install, followed this instruction https://github.com/Kitware/CDash/blob/master/docs/install.md

I also tried #1150, I deleted cdash db, but it seems it broke it more.

**Comment by zackgalbreath** [comment]
Thanks for reporting this issue. This looks like the frontend isn't rendering correctly to me. If you open the web console (typically F12) do you see any error messages you can send our way?

**Comment by williamjallen** [comment]
Nothing in particular stands out to me here.  I refactored a bunch of the underlying code in #1454, so perhaps you can try again with the latest version of master to see if the problem has been fixed.

**Comment by stephenvillagonzalo** [comment]
Hello William,

Thank you, it works now. Just need to upgrade php from 7.3 to version 8.1
