### ISSUE TITLE
Emblem support for CDash

### ISSUE THREAD

**Issue by mcraveiro** [Kitware/CDash#156]
Travis-CI and jenkins provide ways to embed build information into their site in MarkDown documents via "emblems". For example, for Jenkins:

https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin

Is this supported by CDash? Apologies if this has already been asked for - please point me in the right direction.

**Comment by zackgalbreath** [comment]
As far as I know CDash doesn't currently support anything like this.  I agree that it's a good feature request.

**Comment by cpatrick** [comment]
Actually, someone worked on this at some point, but we probably want to revisit it

https://github.com/brennonbrimhall/CBadge

**Comment by mcraveiro** [comment]
@cpatrick this is pretty cool, something like this out of the box on open cdash would make my day :-) However, it is not clear to me how it deals with multiple build agents. I will parse the documentation properly, I may have missed something.

Cheers

**Comment by mcraveiro** [comment]
Actually, this was not very practical as it would require me to run my own CDash instance :-) in the end, I used the Naereen badges and created a generic one. Its not providing any direct status update, its just a link to our CDash [2].

Since this is good enough for now I'll close the issue. Thanks.

[1] https://github.com/Naereen/badges
[2] https://github.com/MASD-Project/dogen
