### ISSUE TITLE
Reorganize repository to use a new 'web' subdirectory

### ISSUE THREAD

**Issue by zackgalbreath** [Kitware/CDash#162]
Currently `DocumentRoot` is meant to be set to the base of the repository.  This is less than ideal, as it allows you to do funny stuff like this:
https://open.cdash.org/tests/CMakeLists.txt

While this example isn't too terrible, you can see how inadvertently exposing our entire repository to the web browser might pose security risks.

Instead, we should create a subdirectory called  `web` and move everything that a web browser is meant to see in there.  This change will require all our production & testing instances to modify their `DocumentRoot` setting, but I think it's worthwhile.

**Comment by jamiesnape** [comment]
I agree.

**Comment by zackgalbreath** [comment]
Resolved by #172.
