### ISSUE TITLE
unable to create a project- display page is blank

### ISSUE THREAD

**Issue by latrivi** [Kitware/CDash#1634]
# Bug report

### Expected Behavior
unable to create a project the page is blank and no eeeors are generated

### CDash Version
 CDash v3.1.0-467-g84c2add8

### Additional Information
<!DOCTYPE html>
<html
    lang="en"
    >
<head >
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="robots" content="noindex,nofollow"/>
    <meta name="csrf-token" content="dp4ECgXp9xpN0liIiYwcBxhQf4U8T1mIQN80P092"/>
    <link rel="shortcut icon" href="[https://xcp-cdash.lanl.gov/favicon.ico](view-source:https://xcp-cdash.lanl.gov/favicon.ico)"/>
    <link rel="stylesheet" type="text/css" href="[https://xcp-cdash.lanl.gov/build/css/3rdparty.css?id=99eb12e8516946bc39bb71aa1c24f056](view-source:https://xcp-cdash.lanl.gov/build/css/3rdparty.css?id=99eb12e8516946bc39bb71aa1c24f056)"/>

    
            <link type="text/css" rel="stylesheet" href="[https://xcp-cdash.lanl.gov/css/jquery.dataTables.css](view-source:https://xcp-cdash.lanl.gov/css/jquery.dataTables.css)"/>
        <link rel="stylesheet" type="text/css" href="[https://xcp-cdash.lanl.gov/build/css/cdash_1691597896009.css](view-source:https://xcp-cdash.lanl.gov/build/css/cdash_1691597896009.css)"/>
        <link rel="stylesheet" type="text/css" href="[https://xcp-cdash.lanl.gov/css/vue_common.css](view-source:https://xcp-cdash.lanl.gov/css/vue_common.css)"/>
        <link rel="stylesheet" type="text/css" href="[https://xcp-cdash.lanl.gov/css/bootstrap.min.css](view-source:https://xcp-cdash.lanl.gov/css/bootstrap.min.css)"/>
        <script src="[https://xcp-cdash.lanl.gov/js/3rdparty.min.js](view-source:https://xcp-cdash.lanl.gov/js/3rdparty.min.js)" type="text/javascript" defer></script>
        <script src="[https://xcp-cdash.lanl.gov/laravel/js/app.js?id=1ffef5bd99f2ea18cdeccfe72de9d773](view-source:https://xcp-cdash.lanl.gov/laravel/js/app.js?id=1ffef5bd99f2ea18cdeccfe72de9d773)" type="text/javascript" defer></script>
    
    
    <title
            > Create Project </title>
</head>
<body
    >

    <div id="app">
                    <div id="header">
    <div id="headertop">
        <div id="topmenu">
            <a href="[https://xcp-cdash.lanl.gov/projects](view-source:https://xcp-cdash.lanl.gov/projects)">All Dashboards</a>
                            <a href="[https://xcp-cdash.lanl.gov/user.php](view-source:https://xcp-cdash.lanl.gov/user.php)">My CDash</a>
            
            <span style="float: right;">
                                    <a href="[https://xcp-cdash.lanl.gov/logout](view-source:https://xcp-cdash.lanl.gov/logout)">Logout</a>
                            </span>
        </div>
    </div>
    <div id="headerbottom">
        <div id="headerlogo">
            <a
                                    href="[https://xcp-cdash.lanl.gov](view-source:https://xcp-cdash.lanl.gov/)"
                            >
                
                                    <header-logo></header-logo>
                            </a>
        </div>

        <div id="headername2">
            <span id="subheadername">
                                                        Create Project
                            </span>
        </div>

        <nav class="projectnav clearfix">
                            <header-nav></header-nav>
                    </nav>

                    <header-menu></header-menu>
            </div>

    </div>
        
        <div id="main_content"
                    >
                                <edit-project v-bind:projectid="0"></edit-project>
                    </div>

                    <div style="flex:1;"></div>

<div id="footer" class="clearfix ng-scope">
    <div id="kitwarelogo">
        <a href="[https://www.kitware.com](view-source:https://www.kitware.com/)">
            <img src="[https://xcp-cdash.lanl.gov/img/kitware_logo_footer.svg](view-source:https://xcp-cdash.lanl.gov/img/kitware_logo_footer.svg)" alt="logo" height="30">
        </a>
    </div>

    <div id="footerlinks" class="clearfix">
        <a href="[https://www.cdash.org](view-source:https://www.cdash.org/)" class="footerlogo">
            <img src="[https://xcp-cdash.lanl.gov/img/cdash_logo_full.svg?rev=2023-05-31](view-source:https://xcp-cdash.lanl.gov/img/cdash_logo_full.svg?rev=2023-05-31)" height="30" alt="CDash logo">
        </a>
        <span id="footertext" class="pull-right">
            CDash v3.1.0-467-g84c2add8f ©&nbsp; <a href="[https://www.kitware.com](view-source:https://www.kitware.com/)">Kitware</a>
            | <a href="[https://github.com/Kitware/CDash/issues](view-source:https://github.com/Kitware/CDash/issues)" target="_blank">Report problems</a>

                            | <a id="api-endpoint">View as JSON</a> 
            
                            | <span id="generation-time"></span> 
            
                            <br>
                <span id="testing-day"></span> 
                    </span>
    </div>
</div>
        
            </div>
</body>
</html>

![image](https://github.com/Kitware/CDash/assets/11186632/67690226-6d98-4e0f-83f6-3ffb3f8f967a)

**Comment by zackgalbreath** [comment]
Closing in favor of #1641
