### ISSUE TITLE
Problem executing 'install' when setting up new CDash server

### ISSUE THREAD

**Issue by dlrdave** [Kitware/CDash#1678]
# Bug report

### Expected Behavior

New CDash server instance to work

### Actual Behavior

docker env file problem, CDash not loading install page

After following the docker instructions, after the very first docker compose command, I got:
```Couldn't read env file: /var/lib/snapd/void/.env.dev```

I continued with trying to load the CDash site in a web browser anyhow, and got this in the apache logs:
```
[Tue Aug 29 09:01:26.511181 2023] [php:warn] [pid 47934] [client XX.XX.XX.XX:41742] PHP Warning:
require(/opt/cdash/CDash-3.2.0-rc1/public/../vendor/autoload.php):
Failed to open stream: No such file or directory in /opt/cdash/CDash-3.2.0-rc1/public/index.php on line 24
[Tue Aug 29 09:01:26.511344 2023] [php:error] [pid 47934] [client XX.XX.XX.XX:41742] PHP Fatal error:
Uncaught Error: Failed opening required '/opt/cdash/CDash-3.2.0-rc1/public/../vendor/autoload.php'
(include_path='.:/usr/share/php') in /opt/cdash/CDash-3.2.0-rc1/public/index.php:24
Stack trace:
#0 {main}
  thrown in /opt/cdash/CDash-3.2.0-rc1/public/index.php on line 24
```

### CDash Version

v3.2.0-rc1 ( downloaded .tar.gz from this link: https://github.com/Kitware/CDash/archive/refs/tags/v3.2.0-rc1.tar.gz )

### Additional Information

This is my first attempt at using docker. I may have something very simple set up incorrectly...?

**Comment by williamjallen** [comment]
Something looks wrong here.  Just to clarify, you got the first error when you ran step 2 [here](https://github.com/Kitware/CDash/blob/master/docs/docker.md#quick-start-testing-installation), right?

It looks like you specified a `.env` file which didn't exist, and CDash didn't start as a result.

I am confused about how you got the apache error if your CDash container didn't start.  Did you cause that error by going to http://localhost:8080, or did you attempt to run a PHP file on your host system somehow?

**Comment by dlrdave** [comment]
> Something looks wrong here. Just to clarify, you got the first error when you ran step 2 [here](https://github.com/Kitware/CDash/blob/master/docs/docker.md#quick-start-testing-installation), right?

Correct


> It looks like you specified a `.env` file which didn't exist, and CDash didn't start as a result.

Yes, that is what it looks like, but the file does exist, and the problem persisted despite my attempts to refer to it by full path (NOT the path in the error message, by the way)

This problem went away when I wiped docker off the machine, and re-installed it from scratch with docker's apt repository and standard ```sudo apt install``` commands, as seen here: https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository
https://docs.docker.com/desktop/install/ubuntu/  

So looks like that bit was a docker problem.



> I am confused about how you got the apache error if your CDash container didn't start. Did you cause that error by going to http://localhost:8080, or did you attempt to run a PHP file on your host system somehow?

I was going to localhost, but was confused by previous attempts to get things up and running without docker, so had apache running on its usual port, but with a "/cdash" symlink pointing into the public directory -- so this is pilot error. Sorry for the noise.


In the end, I did get a "dev" variant of CDash 3.2.0-rc1 working, and running in a docker container, and all the ctest tests passed.

However, I'm still having problems getting a "production" variant up. I had to copy APP_KEY from my manual attempt at getting things working in order for it to show my a working container/cdash in the web browser.

**The last mystery to me here is where does APP_KEY come from in a docker scenario on a fresh install?** Is that just a missing step in the https://github.com/Kitware/CDash/blob/master/docs/docker.md#quick-start-testing-installation ... ?

OK with me if you want to close this as "not a bug" and continue the discussion by some other means.

**Comment by dlrdave** [comment]
> **The last mystery to me here is where does APP_KEY come from in a docker scenario on a fresh install?** Is that just a missing step in the https://github.com/Kitware/CDash/blob/master/docs/docker.md#quick-start-testing-installation ... ?

This [section about setting up a production instance](https://github.com/Kitware/CDash/blob/master/docs/docker.md#production-installation) says to cp .env.example to .env, but nothing about the APP_KEY value, and the .env.example has no APP_KEY value, which leads to different problems spinning up the instance.

I tried ```php artisan key:generate``` but that took me back to an error about failing to open autoload.php.

Everything finally worked for a production instance when I copied the APP_KEY value from my manual attempts to my .env file.

So either I'm not following the directions properly, or the directions are missing something.

**Comment by dlrdave** [comment]
> I tried `php artisan key:generate` but that took me back to an error about failing to open autoload.php.

More info. Was successfully able to run `php artisan key:generate` after making sure the machine I was trying it on had php with all the modules CDash expects installed, and composer, and having run the composer install command from the manual setup install.md page.

Seems like the steps necessary to generate an APP_KEY are not fully covered for a fresh production install in a docker container.

**Comment by williamjallen** [comment]
Glad you got things working.  We're still smoothing out some of the rough edges with the docker deployment process, and it looks like setting the `APP_KEY` is something that needs improvement.

Ideally, there should not be a need for you to install PHP/composer locally.  If you don't need to have access to the key yourself, you could run `docker exec -it cdash php artisan key:generate` to generate it inside the container automatically.  Doing so would mean that all of your sessions would be invalidated, and all of the users would have to sign in again.  You could also log into the container to find the key once it's generated.

**Comment by dlrdave** [comment]
Thanks for the `docker exec -it` suggestion. But.... I can't get the cdash docker container running properly without the APP_KEY, can I?

Feel free to close this issue as "not a bug" or to revise the title of it to be "Improve instructions for fresh production install + docker deployment"

**Comment by williamjallen** [comment]
You could generate the key in a dev container, and then copy it over to a production system as a temporary workaround, but that's not at all the way we *should* be doing things.  I'll close this issue for now, and will add this to my backlog.
