### ISSUE TITLE
Existing API method should be listed

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#169]
Using link like these ones doesn't list the available method:
- http://slicer.cdash.org/api/v1/api.php
- http://slicer.cdash.org/api/v1/

**Comment by williamjallen** [comment]
The REST(ish) API is deprecated and will eventually be removed in favor of the GraphQL API introduced in https://github.com/Kitware/CDash/pull/1772.  CDash offers a GraphiQL instance which allows users to see the fields available.
