### ISSUE TITLE
Failing/Passing graph can no longer click on old results.

### ISSUE THREAD

**Issue by rljacob** [Kitware/CDash#1707]
# Bug report

### Expected Behavior

The "Failing/Passing" graph displays a series of green circles for pass and red x's for fail.  When the mouse hovers over one, it used to display the date and when clicked on, the test output below would switch to the output for that day (if saved).   Also the x-axis showed dates.

### Actual Behavior

Nothing is displayed when mousing over an X or O and clicking on it does nothing.  The x-axis now has 5-digit numbers like "55500"

### CDash Version

CDash v3.2.0-rc1

### Additional Information

Click on one of the circles here:  https://my.cdash.org/test/91638867?graph=status

Browser:   Brave Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (x86_64)](https://brave.com/latest/)

Figure below shows unhelpful x-axis

<img width="953" alt="Screenshot 2023-09-07 at 2 44 39 PM" src="https://github.com/Kitware/CDash/assets/947068/6f0cf917-46a0-41e1-99c2-1b81237b5e7d">

**Comment by rljacob** [comment]
Not sure when this started but pretty sure it worked a few months ago.

**Comment by jcfr** [comment]
I confirm this problem is still happening in the context of `CDash v3.2.0-rc1`, see https://slicer.cdash.org/test/25814986?graph=status

**Comment by jcfr** [comment]
See function `displayGraph()` in `resources/js/components/TestDetails.vue`:

https://github.com/Kitware/CDash/blob/b5abfcb69f57f48c1bf4e365192fe8596959cfb9/resources/js/components/TestDetails.vue#L318-L468

**Comment by williamjallen** [comment]
@sbelsk is actively working on this issue.

**Comment by jcfr** [comment]
Having faced the issue while inspecting a test on `slicer.cdash.org` (based of `v3.2.0-rc2-1-g`d62a9f964), I am looking forward to the fix :rocket:
