### ISSUE TITLE
No link to edit user profile

### ISSUE THREAD

**Issue by dlrdave** [Kitware/CDash#1712]
# Bug report

### Expected Behavior

To be able to edit user profile fields when viewing the "My Profile" page

Some UI way to go to this "profile" page:

![image](https://github.com/Kitware/CDash/assets/185023/730084df-a1dc-4945-9d61-5003e717654e)

### Actual Behavior

There is no UI element to edit user name, institution, or update/change password, even though the page title is "My Profile"

![image](https://github.com/Kitware/CDash/assets/185023/3c170e61-ea81-4cfb-82bf-7cfddccef7c7)

### CDash Version

origin/master at v3.1.0-532-g889b42c3d

**Comment by dlrdave** [comment]
Not sure if this is a separate bug, or an artifact of having gone to the "profile" page manually, and then trying to update my password, but ...

When I click on "Update Password", I get a "419 | PAGE EXPIRED" result.

Let me know if you want me to report a separate bug on that. Or if I just don't have something setup / running properly yet.

**Comment by williamjallen** [comment]
It looks like the only way to get to `/profile` is to be redirected there if your password is expired.  I'm not sure if a link to it was lost, or whether it never existed in the first place, but there should definitely be a link to it on `/user.php`.  #1706 doesn't change any functionality on the UI -- it's purely a one-to-one swap of the client-side rendering engine.  Once it's merged, I'll make a new PR to add a link to the profile page.

As for the 419 issue, I believe that is resolved in #1640.  Feel free to try it out to see if that resolves the problem for you.

**Comment by dlrdave** [comment]
> or whether it never existed in the first place

Well, not sure when it got lost, but it definitely DID exist in the past. We have an old old CDash server we still use right now that is circa 2013 -- some snapshot from master/trunk from between v2.0 and v2.2...

On that version, there is a strip of text based links across the top when you are signed in **and on the user.php page** that say "**All Dashboards | My Profile | Log Out**". Clicking the "My Profile" link takes you to the **editUser.php page** in our old version.


> As for the 419 issue, I believe that is resolved in #1640. Feel free to try it out to see if that resolves the problem for you.

Thanks -- I will do that and let you know.
