### ISSUE TITLE
v3.2.0-rc1 missing columns on the cdash dashboard

### ISSUE THREAD

**Issue by solo-wanderer** [Kitware/CDash#1713]
Hi folks,

I installed the new release candidate v3.2.0-rc1 in my stage environment to test it. 

Followed the installation and upgrade steps from documentation. Copied my production database(using v3.0.3) to my test VM and upgrade its schema.

Once everything was set, I had to change my ".env" `APP_ENV` from production to development. It works, however, I no longer can see the "Configure" and "Build" columns and their respective "Error"&"Warn" columns from my project view, i.e.: <https://my-test-cdash/index.php?project=ProjectName>.

We tried submitting some results to the new dashboard (by modifying CTEST_DROP_SITE in CTestConfig.cmake file). The submissions seems successful when looking at ctest logs, but on the cdash dashboard they seem to miss the Configure, Build, Test columns, and seem otherwise empty.

If I hit the `view as JSON` button, at the bottom right of the page, and compare both environments, I can notice `hasconfiguredata` is set to `false` in my stage environment while on prod is set to `true`. The same applies to `hascompilationdata`. 

Is this happening because I set my `APP_ENV` from production to development? Did I mess up somewhere or is this a bug?

**Comment by williamjallen** [comment]
Do you see any PHP errors or other concerning messages in the logs?  For what it's worth, [open.cdash.org](https://open.cdash.org/index.php?project=CMake) is also running `v3.2.0-rc1`, and the columns on the index page appear to work normally

Switching `APP_ENV` to development mode shouldn't affect this at all.

**Comment by solo-wanderer** [comment]
I didn't see any php errors on the logs. I decided to re-install cdash
v3.2.0-rc1 from scratch and this time it works properly.

Not sure how that happened, or how to reproduce it. I'll post again if I
manage to repro, in the meantime feel free to close this ticket.

Thanks for the fast response

**Comment by williamjallen** [comment]
Great!  Glad to hear things are working now.
