### ISSUE TITLE
 generateCtestConfig.php doesn't generate CTestConfig.cmake file properly in v3.2.0-rc1

### ISSUE THREAD

**Issue by solo-wanderer** [Kitware/CDash#1714]
Using the "Download CTestConfig:" button at the URL <https://cdash.testdomain.com/project/2/edit#Misc> with cdashv3.0.3 generates the following `CTestConfig.make`:
```
## Comments
set(CTEST_PROJECT_NAME "Shared")
set(CTEST_NIGHTLY_START_TIME "21:00:00 America/Toronto")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.myproductiondomain.com")
set(CTEST_DROP_LOCATION "/submit.php?project=Shared")
set(CTEST_DROP_SITE_CDASH TRUE)
```

However, v3.2.0-rc1 generates the following `CTestConfig.make`:
```
## Comments
set(CTEST_PROJECT_NAME Shared)
set(CTEST_NIGHTLY_START_TIME 15:00:00 America/Toronto)

set(CTEST_SUBMIT_URL https://cdash-test.mytestdomain.com/submit.php?project=Shared)

set(CTEST_DROP_SITE_CDASH TRUE)
```

It looks like the new format merged  `CTEST_DROP_METHOD`, `CTEST_DROP_SITE` and `CTEST_DROP_LOCATION` onto a single parameter: `CTEST_SUBMIT_URL`. Nevertheless, attempting to submit test results using the new format,fails outputting this message:
```
Total Test time (real) =  11.84 sec
-- Processing memory checking output:
MemCheck log files can be found here: ( * corresponds to test number)
/home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin/Testing/Temporary/MemoryChecker.*.log
Memory checking results:
SetCTestConfiguration:BuildDirectory:/home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin
SetCTestConfiguration:SourceDirectory:/home/tests/nightly_build/working_copy/Shared/Code/trunk/LibCore
SetCTestConfiguration:ProjectName:Shared
SetCTestConfiguration:DropMethod:http
SetCTestConfiguration:DropSite:(null)
SetCTestConfiguration:DropLocation:(null)
SetCTestConfiguration:IsCDash:TRUE
	Add file: /home/tests/nightly_build/LibCore.utests.Debug.clang.cmake
	Add file: /home/tests/nightly_build/LibCore.utests.Debug.clang.cmake.log
Submit files (using http)
   Using HTTP submit method
   Drop site:http://
   Upload file: /home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin/Testing/20230914-0400/Build.xml to http://?FileName=tests8___LibCore-x86_64-clang-Debug___20230914-0400-Nightly___XML___Build.xml&MD5=d0c1bb3612b570b15113ea18f06c4a31 Size: 1007
   Error when uploading file: /home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin/Testing/20230914-0400/Build.xml
   Error message was: Bad URL
   Problems when submitting via HTTP
```

It appears there is some form of conflict between the two formats.
My assumption is that either `SetCTestConfiguration:DropSite` and `SetCTestConfiguration:DropLocation` are still expecting values previously available on the old `CTestConfig.make` format, or, these are not properly extracted from the new `CTEST_SUBMIT_URL`, i.e. :
```
SetCTestConfiguration:DropSite:(null)
SetCTestConfiguration:DropLocation:(null)
<snip>
Drop site:http://
   Upload file: /home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin/Testing/20230914-0400/Build.xml to http://?FileName=tests8___LibCore-x86_64-clang-Debug___20230914-0400-Nightly___XML___Build.xml&MD5=d0c1bb3612b570b15113ea18f06c4a31 Size: 1007
   Error when uploading file: /home/tests/nightly_build/LibCore-x86_64-clang-Debug-bin/Testing/20230914-0400/Build.xml
   Error message was: Bad URL
```

Also VTK and CMake don't have this new `CTEST_SUBMIT_URL`, ex: <https://gitlab.kitware.com/cmake/cmake/-/blob/master/CTestConfig.cmake?ref_type=heads>

**Comment by josephsnyder** [comment]
@solo-wanderer, thanks for the report.  I think this is more of a CTest issue than a CDash issue but let's make sure: what do you get if you run `ctest --version`?

The `CTEST_SUBMIT_URL` variable was introduced in `3.14`.

**Comment by solo-wanderer** [comment]
Thanks for the reply @josephsnyder, this is almost too embarrassing to admit but I forgot to update `ctest` on my stage environment, my ctest version is indeed older than `3.14`.

Nonetheless, this might prove to be useful information for other users. I can see this mentioned [here](https://github.com/Kitware/CDash/blob/v3.2.0-rc1/CMakeLists.txt#L1) but I didn't find it on the [admin documentation](https://public.kitware.com/Wiki/CDash:Administration#Creating_a_project) or the `install.md`.

If helpful, I can make a PR to add some sort of message regarding minimum `ctest` version, either on the `CTestConfig` file itself(as a comment) or in a different section.

**Comment by solo-wanderer** [comment]
@josephsnyder I love this approach! :100:

I tested it and it works! Nice update
