### ISSUE TITLE
Admin and Test details pages are not properly styled

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#179]
See http://slicer.cdash.org/testDetails.php?test=6938164&build=710983

![screenshot from 2015-11-25 20 52 42](https://cloud.githubusercontent.com/assets/219043/11413409/7cf914f8-93b6-11e5-8530-1d1b76c23bb8.png)

**Comment by jcfr** [comment]
![screenshot from 2015-11-25 23 24 16](https://cloud.githubusercontent.com/assets/219043/11415067/b1eacdc2-93cb-11e5-8e30-ba908508d6e5.png)

**Comment by jcfr** [comment]
@zackgalbreath  Note that this happen with either http://slicer.cdash.org and http://trunk.cdash.org

**Comment by jcfr** [comment]
Interestingly, this doesn't happen on http://testing.cdash.org

**Comment by jcfr** [comment]
![screenshot from 2015-11-25 23 31 00](https://cloud.githubusercontent.com/assets/219043/11415117/9a4c685a-93cc-11e5-9313-1f37575eb7fd.png)

`cdash.css` couldn't be loaded

**Comment by zackgalbreath** [comment]
Thanks for the report.  This should be fixed now.  Please re-open this issue if you find that to not be the case.
