### ISSUE TITLE
Slicer extension CDash submission failed on Windows

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#180]
See enclosed screenshot. I will try to debug further and come up with small script allowing to reproduce the problem.

![slicer-windows-extension-build-are-not-published](https://cloud.githubusercontent.com/assets/219043/11414969/498e3ca6-93ca-11e5-93ae-22f02eee31cb.png)

Cc: @fedorov

**Comment by jcfr** [comment]
Note that since that same VM can build CMake'ified python and submit to https://open.cdash.org/index.php?project=CPython , it doesn;t seem related to the network configuration of the VM .

**Comment by jcfr** [comment]
@zackgalbreath Here is a small project allowing to reproduce the problem: https://gist.github.com/jcfr/cdd2f2672ec0d167d3bd

@pieper @fedorov No Slicer build should be expected on the dashboard. That said, the extension packages should still be published on http://slicer.kitware.com and available on http://download.slicer.org

**Comment by zackgalbreath** [comment]
Sorry about this, CDash was having trouble navigating across a symbolic link on the server.  This problem is fixed now.
