### ISSUE TITLE
Setup: Messages about non-writable backup/upload directory, but no hints on how to fix

### ISSUE THREAD

**Issue by codeling** [Kitware/CDash#2044]
# Bug report

### Expected Behavior

Helpful hints during installation of how things can be configured correctly.

### Actual Behavior

I get the following messages:
```
Your backup directory is not writable, make sure that the web process can write into the directory.
Your upload directory is not writable, make sure that the web process can write into the directory.

Please review the settings of your config.php file below and click install to install the SQL tables.
```

I could find no explanation how to configure backup or upload directory, or where their default location is, in the [CDash Configuration documentation](https://github.com/Kitware/CDash/blob/master/docs/config.md) or in the [provided example .env file](https://github.com/Kitware/CDash/blob/master/.env.example).
Also setting the php upload_tmp_dir permissions to writable by all does not make the second error message go away.
I have then tried setting the CDash directory to be writable by all, still no change. 

So I genuinely have no idea which backup and which upload folder is meant here.

Also, the reference to config.php seems outdated, as, at least to my knowledge, everything now should be configured in the `.env` file, right?

### CDash Version

3.2.3

### Additional Information
![cdash-installation](https://github.com/Kitware/CDash/assets/1629217/a9aebf85-2eca-441d-a0c0-37838e9e992f)

**Comment by codeling** [comment]
Checking the code and in the docs I stumbled upon this page https://github.com/Kitware/CDash/blob/master/docs/submissions.md - and have identified that what setup refers to as "backup directory" seems to have its default location in `storage/app/inbox` - when creating this folder and making it writable by the web server user, the first message shown above goes away. Still looking for the location of the "upload directory" though.

From looking over the code a little I suspect these locations might also be generated automatically when necessary?

**Comment by williamjallen** [comment]
Uploads are stored in `storage/app/upload`.  You can generated this directory (and all of the required storage directories) by running `php artisan storage:mkdirs`.

That command appears to not be getting run for new systems automatically.  I'll open a PR to fix that.

**Comment by williamjallen** [comment]
Closed by https://github.com/Kitware/CDash/pull/2045
