### ISSUE TITLE
CDash 3.3.0 not showing tests column

### ISSUE THREAD

**Issue by zukaitis-lanl** [Kitware/CDash#2111]
# Bug report

### Expected Behavior

I expected to see the Tests column

### Actual Behavior

I did not see the tests column

### CDash Version

3.3.0

### Additional Information

![Screen Shot 2024-03-26 at 12 40 02 PM](https://github.com/Kitware/CDash/assets/142452641/8e811f2d-1def-4abe-bd70-a889cad9df71)

**Comment by zackgalbreath** [comment]
Just a hunch, but this looks like submissions aren't being parsed correctly.

If you have `QUEUE_CONNECTION=database` set in your .env file then you need an async queue worker running separately to parse your XML files (`php artisan queue:work`)

https://github.com/Kitware/CDash/blob/master/docs/submissions.md#asynchronous-submission-parsing

**Comment by williamjallen** [comment]
Closing this now since it's been about 9 months with no further discussion.
