### ISSUE TITLE
Socialite: Bake callback URL defaults into the configuration values for each option

### ISSUE THREAD

**Issue by josephsnyder** [Kitware/CDash#2150]
# Bug report

### Expected Behavior

~~Following the .env examples in the documentation (for GitLab  but likely for others), Filling out the files would allow us to use the OAuth provider to sign in.~~

Ensure that the Socialite Providers have an automatically generated callback URL given to the configuration settings

### Actual Behavior
It errors because the user is not informed that the redirect URL needs to be added as one of the environment variables.  See: https://github.com/Kitware/CDash/discussions/2032

**Comment by zackgalbreath** [comment]
Rather than update the docs, is this something we can bake into CDash itself?

The redirect URI shouldn't need to be a configuration setting, we should be able to construct it automatically based on the value of `app.url` right?

**Comment by josephsnyder** [comment]
@zackgalbreath, it should be.  Thanks for pointing that out!   Following the example in #2144, we should be able to use that same `url()` function here to introduce a default.

**Comment by williamjallen** [comment]
Closed by https://github.com/Kitware/CDash/pull/2180.
