### ISSUE TITLE
Platform icons are not always showing

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#2198]
# Bug report

### Expected Behavior

Always show the platform icon. 

### Actual Behavior

Depending on the configuration of the build on the same platform, sometimes CDash shows the icons (linux / windows) and sometimes not. Particularly, uploading files adds the package icon but causes the platform icon to disappear...

![image](https://github.com/Kitware/CDash/assets/5701372/b4a7625d-3ff9-4b70-9f94-6bab8115aab8)

### CDash Version

v3.3.0 (docker installation)

**Comment by williamjallen** [comment]
Thanks for the report!  It looks like the same thing is happening on open.cdash.org.  I'll investigate.
