### ISSUE TITLE
public website still says 3.1 is current release

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#2205]
Right now, 2024-05-14, this page: https://www.cdash.org/download/

says "The current stable CDash release is 3.1.0".

But looks to me like 3.3 is now out?

**Comment by williamjallen** [comment]
Yep, the website is in dire need of an overhaul.  That's on my to do list, but it will be a couple weeks before I have time to get to it.

**Comment by seanm** [comment]
No need for an overhaul, just change three `1`s to `3`s. :)

**Comment by williamjallen** [comment]
[cdash.org](https://www.cdash.org/download/) has been updated to reflect the new latest version of CDash [v3.4.0](https://github.com/Kitware/CDash/releases/tag/v3.4.0).  I plan to overhaul the rest of the content soon.
