### ISSUE TITLE
Fresh install of CDash 3.4.2 shows version as 3.4.0

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#2280]
# Bug report

### Expected Behavior

After performing a fresh install on a fresh VM, I expect the version number displayed in the app to match the version number of the downloaded tarball.

### Actual Behavior

It shows 3.4.0 instead of 3.4.2.

### CDash Version

3.4.2 from https://github.com/Kitware/CDash/archive/refs/tags/v3.4.2.tar.gz

### Additional Information

OS: FreeBSD 14.1
Apache: 2.4.59
MySQL: 8.0.35
PHP: 8.2.20

Installation process:

```
# service apache24 stop
cdasher.rogue-research.com # tar xvzf CDash-3.4.2.tar.gz
cdasher.rogue-research.com # rm CDash-3.4.2.tar.gz
cdasher.rogue-research.com # chown -R www:www CDash
cdasher.rogue-research.com # chmod -R g+rw CDash
CDash $ composer install --no-dev --prefer-dist
CDash $ export NODE_ENV=production
CDash $ npm install
Note: Here we configured the .env, without ldap and the APP_KEY
CDash $ npm run production
CDash $ php artisan key:generate
CDash $ php artisan migrate
# service apache24 start
```

.env :

```
APP_NAME=CDash
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:**************
APP_URL=https://cdasher.rogue-research.com
DB_DATABASE=cdash
DB_PASSWORD=**********
DB_CONNECTION=mysql
DB_HOST=localhost
DB_USERNAME=cdasher
AUTOREMOVE_BUILDS=true
USE_COMPRESSION=true
QUEUE_CONNECTION=sync
MAIL_FROM_ADDRESS=cdasher@rogue-research.com
MAIL_REPLY_ADDRESS=noreply@rogue-research.com
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
USER_CREATE_PROJECTS = false
```

our site configuration file :

```
<VirtualHost *:443>
    ServerName cdasher.rogue-research.com
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    LogFormat "%h %l %u %{%F %T}t \"%r\" %>s %b \"%{Referer}i\"" rogue
    CustomLog "/var/log/cdash/cdash-access.log" rogue
    ErrorLog "/var/log/cdash/cdash-error.log"
    DocumentRoot /usr/local/etc/apache24/cdasher.rogue-research.com/CDash/public

    SSLEngine on
    SSLCertificateFile path/ourcertificate.pem
    SSLCertificateKeyFile path/ourkey.pem

    <Directory "/usr/local/etc/apache24/cdasher.rogue-research.com/CDash/public">
	SSLRequireSSL
	Require all granted
    AllowOverride All
    </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName cdasher.rogue-research.com
  Redirect permanent / https://cdasher.rogue-research.com/
</VirtualHost>
```

Similar bug reported in the past: #1198.

As you see above, it's a pretty vanilla install, based on CDash's install.md, so I'm not sure what we could have done wrong here...

**Comment by zackgalbreath** [comment]
Hi @seanm,

Thank you for taking the time to write this detailed bug report! I reproduced this situation locally and it is a legitimate bug.

The problem can be tracked back to here:
https://github.com/Kitware/CDash/blob/d247d956c2f06752ab06de5d8c5ccbdb08de6da3/package.json#L3

For installations from release tarballs, we use the version reported in `package.json` when rendering the footer. This wasn't updated for any of the patch releases in the 3.4 series, which explains why your CDash v3.4.2 installation is reporting v3.4.0 in the footer.

**Comment by seanm** [comment]
Thanks for fixing. Now we just gotta find repro steps for you for https://github.com/Kitware/CDash/issues/2272 ...
