### ISSUE TITLE
Removing a build doesn't refresh the UI

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#231]
Clicking on the `Remove this build` link highlighted in the screenshot posted below doesn't refresh the UI.

Reproducible on http://slicer.cdash.org

![screenshot from 2016-01-27 16-13-17](https://cloud.githubusercontent.com/assets/219043/12628410/06bd33b4-c511-11e5-9ec7-156e189c6cf3.png)

**Comment by jcfr** [comment]
Update: This is still an issue on  http://slicer.cdash.org

**Comment by zackgalbreath** [comment]
Thanks for the reminder.  I believe that I have this fixed on slicer.cdash.org via #304.  Can you confirm that it works for you too?

**Comment by jcfr** [comment]
Thanks :+1:  It now works as expected.
