### ISSUE TITLE
Using CDash in conjunction with Traefik

### ISSUE THREAD

**Issue by martin5233** [Kitware/CDash#2333]
# Bug report

### Expected Behavior

After startup, the cdash container should be marked as healthy

### Actual Behavior

After startup, the cdash container is always marked as unhealthy.

### CDash Version

3.5.0rc1

### Additional Information

After #2179 was closed I had hoped to finally be able to use CDash in conjunction with Traefik for certificate management again (we still use 2.6.0, because all later versions failed for us). I found the health check tries to also check the HTTPS connection, but with the wrong URL https://cdash:8080. When a container is marked as unhealthy Traefik refuses to export it.

Please either remove the wrong health check for SSL completely or use the address APP_URL from the .env file.

**Comment by williamjallen** [comment]
The health check was removed entirely in #2334.
