### ISSUE TITLE
Build notes: support downloading a note's contents

### ISSUE THREAD

**Issue by mathstuf** [Kitware/CDash#2337]
# Feature Request

### How can we make CDash better?

The ability to download a note's contents would be nice.

**Comment by williamjallen** [comment]
Are you looking for the ability to get the contents of a note via the API, or do you want a download button on the notes page?

**Comment by mathstuf** [comment]
API would be great for the "CI monitoring" tooling data collection stuff, but download button can work in the meantime.

**Comment by williamjallen** [comment]
https://github.com/Kitware/CDash/pull/2451 will close this issue then, since notes will be available via the GraphQL API.
