### ISSUE TITLE
CDash displaying grayed-out rows

### ISSUE THREAD

**Issue by wadeburgess** [Kitware/CDash#2351]
# Bug report

### Expected Behavior

Results displayed as usual

### Actual Behavior

Numerous reports are only producing grayed-out rows, no true results.

### CDash Version

https://my.cdash.org/index.php?project=E3SM

**Comment by zackgalbreath** [comment]
Thanks for reporting this, @wadeburgess . This problem that occurred while we were attempting to upgrade cdash.org. I think we've identified the source of the issue and dashboard results should be slowly trickling in now.

**Comment by wadeburgess** [comment]
The dashboard was back to good, but now it is not again

**Comment by williamjallen** [comment]
This temporary issue affecting cdash.org sites has been resolved.  Please open another issue if you observe any further issues.
