### ISSUE TITLE
unable to start cdash becasuse of  ERROR  Failed to enter maintenance mode: Please provide a validcache path..

### ISSUE THREAD

**Issue by bonniechen1119** [Kitware/CDash#2456]
# Bug report
unable to start cdash becasuse of  ERROR  Failed to enter maintenance mode: Please provide a validcache path..
### Expected Behavior
unable to start cdash becasuse of  ERROR  Failed to enter maintenance mode: Please provide a validcache path..

use the following compose file
  cdash:
    image: kitware/cdash:v3.5.1
    container_name: cdash
    environment:
      DB_HOST: database
      CYPRESS_CACHE_FOLDER: /cdash/storage/framework/cache
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    volumes:
      - /home/cdash-3.5.1/cdash-storage:/cdash/storage

### Actual Behavior
via guid:https://github.com/Kitware/CDash/blob/master/docs/docker.md

### CDash Version
v3.5.1

### Additional Information

error log:

cdash           | [Tue Sep 24 02:18:29.996966 2024] [core:notice] [pid 18:tid 18] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
cdash           |
cdash           |    ERROR  Failed to enter maintenance mode: Please provide a validcache path..
cdash           |
cdash           |
cdash           | * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
cdash           | *                            INSTALLATION FAILURE!           *
cdash           | *           *
cdash           | * An error occurred while installing CDash and CDash was not able to recover  *
cdash           | * automatically.  If you believe that this is a problem with CDash, please    *
cdash           | * report the error here:           *
cdash           | *           *
cdash           | * -> https://github.com/Kitware/CDash/issues/new           *
cdash           | *           *
cdash           | * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
cdash           |
cdash exited with code 1

**Comment by williamjallen** [comment]
Running `php artisan storage:mkdirs` should fix this issue.

**Comment by williamjallen** [comment]
I just created https://github.com/Kitware/CDash/pull/2459 to eliminate the need to run `php artisan storage:mkdirs` manually for new instances.
