### ISSUE TITLE
why it force redirect to https://172.168.10.9:8080,when we set APP_ENV=production and APP_URL=http://172.168.10.9:8080

### ISSUE THREAD

**Issue by bonniechen1119** [Kitware/CDash#2457]
# Bug report
why it force redirect to https://172.168.10.9:8080,when we set APP_ENV=production and APP_URL=http://172.168.10.9:8080
### Expected Behavior
when we set APP_ENV=production and APP_URL=http://172.168.10.9:8080, and then when we visit cdash websit http://172.168.10.9:8080, it display correct with http://172.168.10.9:8080

### Actual Behavior
currently it will redirect to https://172.168.10.9:8080, and all logo and png will display error because of not correctly ssl

### CDash Version
v3.5.1

### Additional Information
the following is our .env
APP_NAME=CDash
APP_ENV=production
APP_KEY=DV5SQLqXCbpnme4z2pKNujd6gFW9hrj5
APP_DEBUG=true
APP_URL=http://172.16.10.246:8080

LOG_CHANNEL=single

DB_DATABASE=cdash4production
DB_PASSWORD=cdash4production

REGISTRATION_EMAIL_VERIFY=false

QUEUE_CONNECTION=database

**Comment by williamjallen** [comment]
After discussion internally, the historical reasons why HTTPS is forced for production sites are no longer relevant, so I have created https://github.com/Kitware/CDash/pull/2458 to address this issue.

**Comment by bonniechen1119** [comment]
Dear,
after we use the latest cdash image,
It will not force to redirect to https,however after login, it return 419 page expired
