### ISSUE TITLE
Cannot finish CDash installation (v3.5.1)

### ISSUE THREAD

**Issue by kislinsk** [Kitware/CDash#2464]
# Bug report

I followed the installation guide but as soon as I am supposed to finish the installation in a web browser, I get a `The requested URL was not found on this server` error, while the URL changes to `https://ci.local/projects` instead of `https://ci.local/install` as I would have expected according to the installation guide. The latter URL does not work if used directly and yields the same error. It's like the site is not there at all.

I checked the database with the same credentials as CDash and I can confirm that all the tables were created but are empty. I also did a phpinfo() test from the public directory and it works. There is no log output in storage/logs. Webserver logs do not show anything suspicious as well.

I even used the install.sh script in the top-level directory. All steps seem to succeed just like in the manual installation.

### CDash Version

v3.5.1

### Additional Information

Debian 12
Apache
MariaDB
PHP 8

**Comment by williamjallen** [comment]
The `/install` route was removed in #2279 but the bare-metal installation directions were missed.  If you ran `install.sh`, everything should be good to go.  I just opened https://github.com/Kitware/CDash/pull/2467 to clear up any confusion about this.

We strongly recommend using our Docker install for new systems if possible.

**Comment by kislinsk** [comment]
Thanks for your answer. I do not feel like this issue is resolved, though. I also executed the install script, leading to the very same result. I'd really like to understand why nothing shows up. Several other server applications work as intended - it's only CDash giving me trouble unfortunately. Is there some flags or environment variables that I can set to force the underlying framework of CDash to emit some kind of log/error output for example?

**Comment by kislinsk** [comment]
Well, I expect that when following the official instructions and using the official install script I would see at least something in the browser instead of getting a blank page, resp. a server error as described above.

As I can serve my own PHP files from the CDash public directory I assume that the issue is not my server configuration. Also, something is at least trying to redirect to /projects.

**Comment by williamjallen** [comment]
Are you seeing any errors or a blank page at `/projects`?  Perhaps a screenshot of what you see would help.  I'm a little confused about what exactly the issue is here.  The docs were incorrect, but were updated in #2467 to remove the part about `/install`.
