### ISSUE TITLE
Cannot edit groups anymore

### ISSUE THREAD

**Issue by jgfouca** [Kitware/CDash#2507]
# Bug report

### Expected Behavior

I have confirmed that I am still an administrator of https://my.cdash.org/index.php?project=E3SM. I used to be able to hover my mouse over the "Project" tab in the upper right and the dropdown menu gave me the option to edit Groups. This option no longer appears for me.

### Actual Behavior

The Project dropdown menu only has the options "Home" "Documentation" "Bug Tracker" and "Subscribe"

### CDash Version

Whatever version the public my.cdash.org uses.

**Comment by williamjallen** [comment]
@zackgalbreath is my.cdash.org running https://github.com/Kitware/CDash/pull/2503?

**Comment by jgfouca** [comment]
@williamjallen , @zackgalbreath , any thoughts on this? I still cannot access Groups.

**Comment by jgfouca** [comment]
@zackgalbreath , I logged out and back in and that seemed to fix it. I thought I tried that a couple weeks ago but everything looks good now.
