### ISSUE TITLE
`MallocGuardEdges` env var seems to interfere with OS detection

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#2581]
Consider this VTK build submission:

https://open.cdash.org/viewTest.php?onlynotrun&buildid=10040042

<img width="545" alt="image" src="https://github.com/user-attachments/assets/778a4361-cd3e-4f96-bf1b-24d98bc43839">

I enable the environment variable `MallocGuardEdges` to check for memory overruns when tests are run. (see `man malloc` on macOS). This causes a log message, for example:

```console
% MallocGuardEdges=1 sw_vers
sw_vers(33753,0x202738f40) malloc: adding guard pages for large allocator blocks
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
```

versus without it:

```console
% sw_vers
ProductName:		macOS
ProductVersion:		14.7
BuildVersion:		23H124
```

I believe this is why those 3 fields are scrambled. You should be able to look for `ProductName` then take the text after it.

**Comment by williamjallen** [comment]
As far as I am aware, this data comes directly from CTest, so this issue should probably be filed [here](https://gitlab.kitware.com/cmake/cmake/-/issues).

**Comment by seanm** [comment]
Ah ok, it's not always clear to me where the lines are drawn. :)

**Comment by seanm** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/26466

**Comment by seanm** [comment]
And once this is fixed in ctest, will cdash show the correct icon do you think?:

<img width="336" alt="image" src="https://github.com/user-attachments/assets/1d410dfd-b191-4136-a67b-ffdb184c4741">

**Comment by williamjallen** [comment]
It should, yes.  The icon is determined directly from the operating system data provided by CTest.
