### ISSUE TITLE
New nightly start time discrepancy in release

### ISSUE THREAD

**Issue by ngladitz** [Kitware/CDash#297]
Yesterday I upgraded our CDash installation from

20ee5c1486b87128b6898bae884716014a7f65f9 
to 
c9b921f4b33c249fea6982896df23659e180521c (release).

Our builds from last night have now been sorted into yesterday instead of today like they had been before.

Configured nightly start time for all projects is 20:00 UTC (22:00 CEST - localtime).
One of the nightly build's build time is e.g. Apr 8 01:05 CEST (Apr 7 23:05 UTC).

Did something change here that I must account for or is this an unintentional break?

**Comment by zackgalbreath** [comment]
My hunch is that this is a timezone issue.  Try adding a line like this to your ```config.local.php``` file:

    date_default_timezone_set('America/New_York');
[Here's a list of supported timezones](http://php.net/manual/en/timezones.php).

**Comment by ngladitz** [comment]
date_default_timezone_get() already seems to correctly return "Europe/Berlin" which is what I would have set it to otherwise.

I can try setting it explicitly from config.local.php too in case it gets clobbered somewhere else I suppose but I am not hopeful.

**Comment by ngladitz** [comment]
One of the submitted Build.xml e.g. has:

  BuildStamp="20160407-2000-Nightly"
and
  <StartDateTime>Apr 08 01:05 CEST</StartDateTime>
  <StartBuildTime>1460070334</StartBuildTime>

But for some reason the build table in the database shows a starttime of "2016-04-07 19:59:59".
In fact all build table rows for that night seem to have that same starttime which basically is one second before my nightly start time.

Entries from before the upgrade show less constant/incorrect times like e.g. "2016-04-06 23:05:21".

Any idea where those "starttime"s might come from?

**Comment by zackgalbreath** [comment]
This sounds like a real bug to me.  Would you be able to share your CTest driver script?

**Comment by ngladitz** [comment]
The script is generated per build and is rather unwieldy / long but here it is: [client.txt](https://github.com/Kitware/CDash/files/210277/client.txt)

**Comment by zackgalbreath** [comment]
Unfortunately I'm still having trouble reproducing this issue on my end.  Could you send me a set of XML files for one of these builds?

**Comment by ngladitz** [comment]
I had to slightly edit the files (e.g. remove the bulk file upload content from Upload.xml) but I don't think I broke anything significant: [20160407-2000.zip](https://github.com/Kitware/CDash/files/210407/20160407-2000.zip)

**Comment by zackgalbreath** [comment]
Can you try cherry-picking the commit from #300 and let me know if it fixes the problem for you?

**Comment by ngladitz** [comment]
Thanks, done. I'll report back when I've got the results.

**Comment by ngladitz** [comment]
Seems to have fixed the issue for me.
The "starttime"s in the database look normal again and builds were properly sorted into today.
Thanks again!
