### ISSUE TITLE
API: Add endpoint similar to "filter" functionality

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#301]
This would help me to get the start time, duration, etc ... of all extensions build associated with  a given group (e.g `Extensions-Nightly`) and site (e.g `factory-south-w`) and get a better understanding of the  bottleneck of a specific machine.

Now since the page are now paginated, it is not possible to simply parse the HTML using BeautifulSoup python module. (e.g https://github.com/fedorov/CDashWrangler )

See http://slicer.cdash.org/index.php?project=Slicer4&date=2016-04-11&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Extensions-Nightly&field2=site&compare2=61&value2=factory-south-w

Cc: @fedorov @lassoan @thewtex

**Comment by thewtex** [comment]
+1

**Comment by zackgalbreath** [comment]
> http://slicer.cdash.org/index.php?project=Slicer4&date=2016-04-11&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Extensions-Nightly&field2=site&compare2=61&value2=factory-south-w

You can put ``api/v1`` before index.php to see the JSON data that's used to render the page:

http://slicer.cdash.org/api/v1/index.php?project=Slicer4&date=2016-04-11&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=63&value1=Extensions-Nightly&field2=site&compare2=61&value2=factory-south-w

**Comment by fedorov** [comment]
@zackgalbreath this is excellent, thank you very much!

**Comment by jcfr** [comment]
:8ball:  Thanks @zackgalbreath 

Should I update the [wikipage](http://www.vtk.org/Wiki/CDash:API) ?

**Comment by zackgalbreath** [comment]
> Should I update the wikipage ?

Good suggestion, I just added a new section to that page describing this feature.

**Comment by jcfr** [comment]
Great :cake:
