### ISSUE TITLE
Database schema doesn't match with the version of CDash which installed it

### ISSUE THREAD

**Issue by bbenoist** [Kitware/CDash#314]
Hi,

After installing CDash from the `release` branch, I got the following error message when navigating to `viewProjects.php`:

```
The current database schema doesn't match the version of CDash you are running, upgrade your database structure in the  Administration/CDash maintenance panel of CDash
```

![image](https://cloud.githubusercontent.com/assets/2091902/14648961/3714cb72-0665-11e6-9329-46a696dd4475.png)

Problem is that the database has been initialized by the exact same CDash instance (I clicked on `All projects` after `install.php` and new project creation steps) 😕 

Clicking on the `Upgrade CDash` button of the `upgrade.php` is not fixing the issue.

**Comment by bbenoist** [comment]
Looks like it was a reverse proxy issue. Sorry for polluting GH issues.

After some nginx configuration changes and full reinstall everything seems to be running fine now.

**Comment by lrineau** [comment]
@bbenoist What was the issue, and the solution? I have the same issue, also with a reverse proxy.

**Comment by bbenoist** [comment]
Sorry @lrineau but I don't remember what was the Nginx problem and I cannot retrieve the config files since I changed company since then 😕  Good luck finding a solution!
