### ISSUE TITLE
slicer.cdash.org: CDash hangs / slow loading

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#359]
See http://slicer.cdash.org/index.php?project=Slicer4&date=2016-05-30

The Items per page for `Extensions-Experimental` was set to `All`

Clicking on slow loading allow the page to fully load.

Changing the Items per page for `Extensions-Experimental` to `10` avoids the hang.

![screenshot from 2016-05-30 15-13-20](https://cloud.githubusercontent.com/assets/219043/15656890/b2362cd6-2679-11e6-8f6a-70abf391c4b5.png)

![screenshot from 2016-05-30 15-13-47](https://cloud.githubusercontent.com/assets/219043/15656889/b235b99a-2679-11e6-9441-6976db5ed9de.png)

**Comment by jamiesnape** [comment]
Browser? OS? Seems fine with Chrome and Safari for me?

**Comment by jcfr** [comment]
Thanks for looking into the issue.

After setting all selectors to `All` and trying to reload the [page](http://slicer.cdash.org/index.php?project=Slicer4&date=2016-05-30), I was able to reproduce the issue.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

![screenshot from 2016-06-08 16-25-56](https://cloud.githubusercontent.com/assets/219043/15909760/d10401d8-2d95-11e6-8d1e-365ee19a94e0.png)

**Comment by zackgalbreath** [comment]
I have a fix live on open.cdash.org that helps to alleviate this problem.  I'll try to upgrade slicer.cdash.org soon.

**Comment by jcfr** [comment]
This is great news. Let me know when you have a chance to update slicer.cdash.org

In the mean time, is there any PR I should review ?

**Comment by zackgalbreath** [comment]
Closing this old issue as I believe the problem has been addressed.  Please let me know if that's not the case.
