### ISSUE TITLE
Show the number of builds in each build group on the UI

### ISSUE THREAD

**Issue by jamiesnape** [Kitware/CDash#394]
Maybe just in parentheses after the name. I would love statistics like average build time somewhere too, but a simple count would still be useful.

**Comment by zackgalbreath** [comment]
I like this idea.

Any opinion on how we should handle "expected but missing" builds?  The naive approach would have CDash including these in the total number of builds.  We could explicitly exclude them instead, or report something like "X of Y builds".

**Comment by jamiesnape** [comment]
Either (X/Y) or (X of Y) sound good to me.

**Comment by zackgalbreath** [comment]
Implemented in #402
