### ISSUE TITLE
my.cdash.org is not accepting file uploads

### ISSUE THREAD

**Issue by ned14** [Kitware/CDash#404]
http://my.cdash.org/index.php?project=Boost.AFIO is not showing files uploaded. The cdash error log shows this:
```
 Error reported on 2016-07-27 04:12:00 for build #1013318
(/data/www/CDashMy/xml_handlers/upload_handler.php:348 - endElement): UploadFile model - Failed to insert row associated with file: 'afio_v2_binaries_win64.tar.xz'

 Error reported on 2016-07-27 04:11:59 for build #1013318
(/data/www/CDashMy/models/uploadfile.php:50 - Insert): Filesize is not set
```
http://my.cdash.org/viewErrorLog.php?buildid=1013318&projectid=964&date=

To my best knowledge, I am not doing anything wrong. cmake doing the upload from appveyor is 3.5.2.

**Comment by zackgalbreath** [comment]
I just tested uploading a simple file to your project and it worked for me:
http://my.cdash.org/viewFiles.php?buildid=1015119

This build was generated using CMake v3.6.  Here's what the relevant portion of my CTest driver script looks like:
```
ctest_start(Experimental)
ctest_configure()
ctest_build()
ctest_upload(FILES "/tmp/tmp.txt")
ctest_submit()
```

Are you doing something similar when trying to upload `afio_v2_binaries_win64.tar.xz`?

**Comment by ned14** [comment]
You can see the cdash upload script at https://github.com/ned14/boost.afio/blob/master/.ci.cmake but the relevant part is:

```
ctest_start("Experimental")
ctest_configure()
ctest_build()
ctest_test()
merge_junit_results_into_ctest_xml()
if(WIN32)
  if(EXISTS build/bin/Release/afio_dl-2.0-Windows-x64-Release.dll)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfJ afio_v2_binaries_win64.tar.xz
      doc
      include
      Readme.md
      release_notes.md
      build/lib/Release/afio_sl-2.0-Windows-x64-Release.lib
      build/lib/Release/afio_dl-2.0-Windows-x64-Release.lib
      build/bin/Release/afio_dl-2.0-Windows-x64-Release.dll
    )
    ctest_upload(FILES afio_v2_binaries_win64.tar.xz)
  endif()
else()
  if(EXISTS build/bin/Release/afio_dl-2.0-Linux-x86_64-Release.so)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfJ afio_v2_binaries_linux64.tar.xz
      doc
      include
      Readme.md
      release_notes.md
      build/lib/Release/afio_sl-2.0-Linux-x86_64-Release.a
      build/bin/Release/afio_dl-2.0-Linux-x86_64-Release.so
    )
    ctest_upload(FILES afio_v2_binaries_linux64.tar.xz)
  endif()
endif()
ctest_submit()
```

Is it possible that cdash dislikes the `.tar.xz` file extension?

**Comment by mathstuf** [comment]
You should check the return value of the `execute_process` bits. The cmake on that machine might not have xz support?

**Comment by ned14** [comment]
It does have xz support, but to rule that out I changed it to a tar.gz. I also print the result of the tar (it succeeds), and for good measure I list the directory on Appveyor before the upload where the pertinent entry appears as:
```
08/03/2016  08:12 AM         3,959,911 afio_v2_binaries_win64.tar.gz
```
So a valid tar.gz file is definitely being generated, and around 4Mb is indeed correct.

Same error appears though on cdash:
```
 Error reported on 2016-08-03 04:12:18 for build #1018049
(/data/www/CDashMy/models/uploadfile.php:50 - Insert): Filesize is not set

 Error reported on 2016-08-03 04:12:18 for build #1018049
(/data/www/CDashMy/xml_handlers/upload_handler.php:348 - endElement): UploadFile model - Failed to insert row associated with file: 'afio_v2_binaries_win64.tar.gz'
```
It seems to my ignorant understanding that this is simply a case of ctest not setting the file size in the file upload request, or cdash forgets the file size in between receiving the upload and inserting it into its database? I agree that your test upload worked, maybe it's a file size thing? Is there some small limit for HTTP PUT or is ctest using HTTP POST?

Could it even be that on Windows only ctest sends CRLF in the HTTP request headers for the file upload? That might mangle the upload file size parsing, and cause "Filesize is not set".

**Comment by mathstuf** [comment]
HTTP Request headers are always supposed to be CRLF. You still should really check the return value of `execute_process`.

**Comment by ned14** [comment]
@mathstuf As you'll see at https://ci.appveyor.com/project/ned14/boost-afio, the return value from execute_process is being printed. That is not the cause of this issue.

**Comment by ned14** [comment]
@mathstuf `execute_process()` now has its error code return trapped and a fatal error issued if failure

**Comment by zackgalbreath** [comment]
@ned14 can you provide me an example file that's failing to upload for you?  With that I should be able to get to the bottom of what's going wrong here.

**Comment by ned14** [comment]
I just ran `ctest -S .ci.cmake -V` locally here and it failed to upload to cdash this binary which I've pushed here instead: https://dedi4.nedprod.com/static/files/afio_v2_binaries_win64.tar.gz

**Comment by zackgalbreath** [comment]
Thanks for the file (and for your patience).

From my experiments, this works:
```ctest_upload(FILES "/path/to/afio_v2_binaries_win64.tar.gz")```
http://my.cdash.org/viewFiles.php?buildid=1026608

But this does not:
```ctest_upload(FILES afio_v2_binaries_win64.tar.gz)```

Please try passing a full path in quotes to ```ctest_upload``` and let us know if the problem persists for you.

**Comment by ned14** [comment]
By gum, yes you've solved it. It is now working once the path is absolute.

Some observations:

1. ctest does check if the file exists at the point of doing ctest_upload() but then fails with no error if that file has vanished by the time of the submit. That should be fixed.

2. There is a strong argument that ctest_upload() should make absolute the path it stores for ctest_submit() to use.

3. On the server the error message reported was not useful either.

But all said, you've unblocked me now. I am very grateful, thank you.
