### ISSUE TITLE
CDash build graph axes are confusing

### ISSUE THREAD

**Issue by jamiesnape** [Kitware/CDash#412]
From @david-german-tri in RobotLocomotion/drake#3096:
> Example: https://drake-cdash.csail.mit.edu/buildSummary.php?buildid=74284
>
> There are left and right y-axes, both of which are labeled in minutes. The left axis (I think) corresponds to the curves with actual time dimensions. The right axis (I think) corresponds to the curves that are dimensionless, and the "minutes" label just shouldn't be there.
>
> Given that the scales are not similar even among curves that have the same units, I suggest it would be more useful just to show four separate graphs.

**Comment by BetsyMcPhail** [comment]
Fixed by #415
