### ISSUE TITLE
Revision filtering does not work

### ISSUE THREAD

**Issue by mathstuf** [Kitware/CDash#435]
Going to a URL created by the filter form using the `revision` field just takes me back to the project list. [Example link created by the filter form](https://open.cdash.org/index.php?compare1=63&filtercount=1&showfilters=1&limit=100&field1=revision&compare1=61&value1=baeb8fe3fe98fc1039a1baaba96f4dee507e187e).

@danlamanna @billhoffman

**Comment by zackgalbreath** [comment]
Looks like it dropped the project parameter somehow...  Can you walk me through how you created this URL?  I'm having trouble reproducing it using the "Create Hyperlink" button.

https://open.cdash.org/index.php?project=CDash&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=2c6d4ee

**Comment by mathstuf** [comment]
- click the `cdash` link [here](https://gitlab.kitware.com/paraview/paraview-superbuild/merge_requests/222/builds) (it's the `Build #…` text);
  - change `showfilters` to be 1 in the URL bar;
  - remove filter2 (the dropdowns are empty here if it matters);
  - change filter1 to be `Revision` and `is` with value `baeb8fe3fe98fc1039a1baaba96f4dee507e187e` (obtained from the last kwrobot comment on the above MR);
  - click `Apply` → back to the project list.

Both the `Create Hyperlink` and clicking `Apply` had the same behavior for me.

**Comment by zackgalbreath** [comment]
Aha, I see the problem.  Apparently the order of the URL parameters matters here.  It shouldn't, so I'll work on fixing this.

In the meantime, do we have control over the process that's creating that link to CDash?  If so, it should look like this instead:

https://open.cdash.org/index.php?project=ParaView&filtercount=2&showfilters=1&filtercombine=and&field1=revision&compare1=63&value1=baeb8fe3&field2=buildstarttime&compare2=83&value2=20161108T133939

**Comment by mathstuf** [comment]
Yes and no. Buildbot makes the link, but the parameter order is sorted by Python's dictionary key ordering.

**Comment by zackgalbreath** [comment]
> Buildbot makes the link, but the parameter order is sorted by Python's dictionary key ordering.

Makes sense.  In that case, the only change I suggest is specifying the fields as:
```
buildname
buildstartttime
```

instead of:
```
buildname%2Fstring
buildstarttime%2Fdate
```

This will fix the "blank field" UI display issue you noticed.

**Comment by zackgalbreath** [comment]
https://github.com/Kitware/CDash/pull/436

**Comment by mathstuf** [comment]
This is fixed I think?
