### ISSUE TITLE
Build history links have typo in URL

### ISSUE THREAD

**Issue by Lucy-tri** [Kitware/CDash#443]
I want the build history for a particular machine.
Let's start at a particular build number, like:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-clang-continuous-debug/1328/
Click on "view in CDash".
Click on the build name in the table (linux-clang-continuous-debug-drake).
Click on "show build history":  then a table appears with clickable links. 
If I click a link (the time of the build), it goes to a URL with a typo in the URL:  `buidlSummary` , which should be `buildSummary`.

**Comment by zackgalbreath** [comment]
Thanks for pointing this out!  This was fixed in PR #444
