### ISSUE TITLE
Submission processing does not occur on Nginx with CDASH_ASYNC_WORKERS > 1

### ISSUE THREAD

**Issue by jamiesnape** [Kitware/CDash#462]
Literally nothing happens, no errors, but no processing.

**Comment by zackgalbreath** [comment]
Does the loop start if you manually trigger it with your web browser?

//CDash/ajax/processsubmissions.php?projectid=1&force=1

**Comment by jamiesnape** [comment]
Yes.

**Comment by zackgalbreath** [comment]
And the loop automatically starts for `CDASH_ASYNC_WORKERS < 2`?

**Comment by jamiesnape** [comment]
Yes, that is the configuration that we currently use.

**Comment by zackgalbreath** [comment]
Probably something funny going on with [curl_request_async](https://github.com/Kitware/CDash/blob/master/include/do_submit.php#L506) then.  I'll see if I can reproduce this locally.

**Comment by zackgalbreath** [comment]
fixed by #475
