### ISSUE TITLE
Revision query on CDash has an implicit "today" filter on it

### ISSUE THREAD

**Issue by mathstuf** [Kitware/CDash#472]
Compare [this revision query](https://open.cdash.org/index.php?project=ParaView&filtercombine=and&filtercount=1&showfilters=1&field1=revision&compare1=61&value1=4a66e02488c3727f4f5d24eb22cef42efd4dae81) with [this one with a date range included](https://open.cdash.org/index.php?project=ParaView&filtercount=2&showfilters=1&filtercombine=and&field1=revision&compare1=61&value1=4a66e02488c3727f4f5d24eb22cef42efd4dae81&field2=buildstarttime&compare2=83&value2=2017-01-01).

**Comment by mathstuf** [comment]
Actually I guess this is consistent with other filters, but other time filters are already "magic" which remove the implicit date restriction; maybe revision should do so as well?

**Comment by zackgalbreath** [comment]
Like you noticed, this is kinda on purpose.  If you're looking at a particular day's worth of builds and decide to filter on "has more than 0 build errors", you wouldn't suddenly want to see all failing builds in the database.

That being said, I agree that if you're searching on revision you're probably not married to a particular day.  This should be an easy fix.  In the meantime, [here's the workaround](https://open.cdash.org/index.php?project=ParaView&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=revision&compare1=61&value1=4a66e02488c3727f4f5d24eb22cef42efd4dae81&field2=buildstarttime&compare2=84&value2=now).

**Comment by mathstuf** [comment]
Do you have a timeframe for a fix to be deployed? (Wondering how long the workaround will have to live.)

**Comment by zackgalbreath** [comment]
We can get this done today

**Comment by zackgalbreath** [comment]
This changed has been merged and deployed to open.cdash.org.
