### ISSUE TITLE
Graph not displayed for custom measurement names containing a space

### ISSUE THREAD

**Issue by markdewing** [Kitware/CDash#508]
The problem is the sanitizing in public/ajax/showtestmeasurementdatagraph.php, on line 26:
```$measurement = preg_replace('/[^\da-z]/i', '', $_GET['measurement']);```
This removes everything from the name that is not a digit or character.

A space in the measurement name seems to work everywhere else - upload, display on the test page, storage in the database.

**Comment by markdewing** [comment]
One possible narrow fix is to add space to the allowed characters regex and add a call to trim to remove the leading and trailing white space.   For a better fix, the characters allowed here should be the same as allowed on upload (or the upload should check and restrict the allowed characters in the name).

```javascript
26c26
< $measurement = preg_replace('/[^\da-z]/i', '', $_GET['measurement']);
---
> $measurement = trim(preg_replace('/[^\da-z ]/i', '', $_GET['measurement']));
```

Also, there are a series of calls on line 27 to escape various characters, but it looks like all those characters will be removed in line 26.

**Comment by zackgalbreath** [comment]
@markdewing could you test out #516 and verify that it fixes the problem for you?

**Comment by markdewing** [comment]
Yes, #516 fixes the issue.  Thanks!
