### ISSUE TITLE
Filtering by revision is not restricted to the most recent submissions

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#517]
See http://slicer.cdash.org/index.php?project=Slicer4&date=2017-04-17&filtercount=1&showfilters=1&field1=revision&compare1=61&value1=25933

![screenshot from 2017-04-17 11-03-53](https://cloud.githubusercontent.com/assets/219043/25092870/9ac9fef6-235d-11e7-8887-b1eeff9a2095.png)

**Comment by jcfr** [comment]
In comparison, filtering by Group name effectively list the most recent submissions.

http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly-Packages

![screenshot from 2017-04-17 11-09-59](https://cloud.githubusercontent.com/assets/219043/25093050/7af8f5b8-235e-11e7-82bc-9e57f2edbd91.png)

**Comment by zackgalbreath** [comment]
As you noticed, some filters implicitly override default date clause of "builds from today only".  These are:
* Build Start Time
* Build Stamp
* Revision

Revision was added to the list due to #472.

**Comment by jcfr** [comment]
Thanks for the quick reply.

To select only "build from today" for revision, is it reasonable to use a filter like this:

```
http://slicer.cdash.org/index.php?project=Slicer4& \
  filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2& \
  field1=revision&compare1=61&value1=25933& \
  field2=buildstarttime&compare2=83&value2=YYYY-DD-MM
```

where `YYYY-DD-MM` is somethine like `new Date().toISOString().slice(0,10)` ?

* `83` ->  `DATE_IS_AFTER`

**Comment by zackgalbreath** [comment]
Yes, that looks pretty good.

It looks like your nightly start time is 03:00 UTC.  So if you want to be more precise, you could do something like this:

http://slicer.cdash.org/index.php?project=Slicer4&date=2017-04-17&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=revision&compare1=61&value1=25933&field2=buildstarttime&compare2=83&value2=2017-04-17%2002%3A59%3A59%20UTC

("Build Start Time"  "is after" "2017-04-17 02:59:59 UTC")

If you're trying to find builds from a previous day you would also need a corresponding "is before" filter clause.

**Comment by jcfr** [comment]
Makes sense. Thanks for the clarification.
