### ISSUE TITLE
Page load time is extremely slow

### ISSUE THREAD

**Issue by thewtex** [Kitware/CDash#538]
This is most noticeable for large projects like ITK, VTK.

**Comment by zackgalbreath** [comment]
Which page, index.php?

**Comment by thewtex** [comment]
Yes, e.g.

  https://open.cdash.org/index.php?project=Insight

I load this page multiple times per day. According to Chrome Dev tools, it takes 3.8 seconds to be fully rendered.
![insighttiming](https://cloud.githubusercontent.com/assets/25432/26214381/319511de-3bca-11e7-86d9-52f89e41b989.png)

**Comment by jcfr** [comment]
Similar issue with Slicer dashboard, @lassoan do you have some more details about your use case ?

**Comment by lassoan** [comment]
Loading times are varying, but when I'm measuring the time (by reloading pages several times), displaying full Slicer dashboard loading time is about 30-40 seconds on Edge browser and about 10 seconds on Chrome. Usually I find Edge has the same speed or slightly faster than Chrome, so this huge difference is quite surprising.
I'm going to use Chrome more for browsing the Slicer dashboard and let you know if I experience slowdowns with this browser as well.

**Comment by williamjallen** [comment]
I made several performance improvements which have been installed on [open.cdash.org](https://open.cdash.org), and will be included in the CDash 3.2 release.  Please file a new issue if you continue to experience slowness of any kind.  In particular, reporting the specific page you are trying to access is helpful.
