### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by marcioivan** [Kitware/CDash#550]
After following the instructions to install, when I try to access CDash, I get the following error:

Fatal error: Unknown: Failed opening required '/projects/CDash_release_bin/prepend_coverage.php' (include_path='.:') in Unknown on line 0

This seems to be something added on the last pull made in May on the prebuilt branch

**Comment by zackgalbreath** [comment]
Thanks for letting us know.  I just refreshed the prebuilt branch to the latest version of master.  While doing so I fixed the offending `.htaccess` file.

**Comment by marcioivan1** [comment]
Thanks, now it works. But is it expected to be getting the "Undefined index error" on the Settings > Measurements page?

**Comment by emmenlau** [comment]
Since the core problem is solved and this issue is quite dated, can it be closed?
