### ISSUE TITLE
Provide full docker image to faciliate use

### ISSUE THREAD

**Issue by bitminer49er** [Kitware/CDash#562]
Provide a full official docker image kitware/cdash at

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=%22kitware%2Fcdash%22&starCount=0

to provide ease of use

This is close to but not exactly related to:

https://github.com/Kitware/CDash/issues/302

as 302 is related to testing and development not simple use.

**Comment by zackgalbreath** [comment]
https://hub.docker.com/r/kitware/cdash/
