### ISSUE TITLE
Some time zones are not properly interpreted

### ISSUE THREAD

**Issue by scottwittenburg** [Kitware/CDash#579]
A timezone string generated by CTest on some Windows systems (AppVeyor build images in this case) is not properly handled by CDash: `Pacific Daylight Time`.

The attached image shows the xml uploaded to CDash on one occasion.  Since that xml contains a `<StartTime>` tag, it seems that element could be used instead of the `<StartDateTime>` (which has to be parsed) in order to compute the actual start time.  This might remove some ambiguity and perhaps make the interpretation of start time less fragile.

![rdp-2017-update-xml](https://user-images.githubusercontent.com/6527504/30676389-28373c4e-9e43-11e7-9dec-c21e72951e9c.png)

**Comment by zackgalbreath** [comment]
Fixed in #594
