### ISSUE TITLE
PostgreSQL Query error on manageBuildGroup.php

### ISSUE THREAD

**Issue by ngladitz** [Kitware/CDash#580]
I am running 29c961c93171dc42d28cb9b177f40e7ceebc32c8 (current prebuilt).

On `manageBuildGroup.php` I get: `Error: Database error during site lookup`

My `log/cdash.log` contains:
```
[2017-09-21 07:34:27] cdash.ERROR: ERROR:  column "s.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT b.siteid, s.name
                         ^
#0 /var/www/CDash/public/api/v1/manageBuildGroup.php(121): pdo_execute(Object(PDOStatement))
#1 {main}
 {"function":"pdo_execute","pid":31076} 
```

**Comment by bryonbean** [comment]
@ngladitz It sounds like a MySQL configuration problem. I seem to remember having a similar one. Have you read the documents [here](https://public.kitware.com/Wiki/CDash:Configuration#SQL_Database) about MySQL configuration? Make sure to read this carefully, especially the part about MySQL strict mode, then, if you're configured correctly or still having problems after let me know.

**Comment by bryonbean** [comment]
Never mind sorry, just read that you're using PostgreSQL, not sure how I missed that.

**Comment by bryonbean** [comment]
@ngladitz  PR https://github.com/Kitware/CDash/pull/581 addresses/fixes the issue. However the endpoint currently works as expected despite the error output. Thanks for pointing it out!

**Comment by ngladitz** [comment]
Thanks for the quick fix!

**Comment by williamjallen** [comment]
Closing this issue since it seems to have been fixed by https://github.com/Kitware/CDash/pull/581.
