### ISSUE TITLE
could not create handler based on xml content (ctest_parse)

### ISSUE THREAD

**Issue by davydden** [Kitware/CDash#599]
I am trying to set-up a private server with CDash for internal projects. All appears be working (CDash is installed and configured, admin user is there, we can create projects, etc). 

The issue is at the submission state of tests via
```
$ ctest -D Experimental
```
in the logs one can see:
```
cdash.ERROR: error: could not create handler based on xml content {"function":"ctest_parse","pid":12967}
```

`CTestConfig.cmake` is the default downloaded from CDash server.

I am not sure whether it some bug in `php` scripts or issue with our configuration. Either way i would appreciate any hints where to dig.

EDIT: things work with `my.cdash.org`, so it must be related to some config...

**Comment by zackgalbreath** [comment]
Could you share the XML files that CTest generated?  These should still be in your binary directory, under `Testing/<date-time>/`

**Comment by davydden** [comment]
sorry for the noise, it turned that it was related to CDash installation. On the second examination of logs, we noticed 

> script '/var/www/html/submit.php' not found or unable to stat


What our sys-admin explained to me is that he had to do both of those steps on the wiki

> Only CDash's public subdirectory should be exposed to the web. There are two main ways to accomplish this:
> 1. Create a symbolic link from DocumentRoot to CDash/public.
> 2. Configure DocumentRoot to point directly to CDash/public.

then everything worked as expected.
