### ISSUE TITLE
intermittently injected javascript causes bad page layout

### ISSUE THREAD

**Issue by SupremeGit** [Kitware/CDash#606]
Hi Ppls,
I've just setup cdash 2.4.0-prebuilt and have submitted several VTK builds. But when I view the builds at: CDash/index.php?project=VTK+Nightly" the behaviour is odd:

  - Often, the page displays incorrectly, and when I reload the page, it generally *stays bad*. 
  - But if I then go to the "Settings" icon, and switch to "Advanced View", the dashboard usually comes good. 
  - And if Advanced View has fixed it, and I then toggle back to "Simple View", simple view is fixed also. 
  - And if I then reload the page, it stays good. For a while. 
  - But eventually at some point, when I reload, it is bad again.

I've saved the HTML from two of these occasions, done a diff, and found the pages that display *badly* are absolutely identical except they have some extra javascript injected.

Where the *good* page has just this:
`           <img src="img/settings.png"/>`

The *bad* pages has this:
```
          <script pagespeed_no_defer="" type="text/javascript">//<![CDATA[
(function(){var g=this,h=function(b,d){var a=b.split("."),c=g;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===d?c[e]?c=c[e]:c=c[e]={}:c[e]=d};var l=function(b){var d=b.length;if(0<d){for(var a=Array(d),c=0;c<d;c++)a[c]=b[c];return a}return[]};var m=function(b){var d=window;if(d.addEventListener)d.addEventListener("load",b,!1);else if(d.attachEvent)d.attachEvent("onload",b);else{var a=d.onload;d.onload=function(){b.call(this);a&&a.call(this)}}};var n,p=function(b,d,a,c,e){this.f=b;this.h=d;this.i=a;this.c=e;this.e={height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth};this.g=c;this.b={};this.a=[];this.d={}},q=function(b,d){var a,c,e=d.getAttribute("pagespeed_url_hash");if(a=e&&!(e in b.d))if(0>=d.offsetWidth&&0>=d.offsetHeight)a=!1;else{c=d.getBoundingClientRect();var f=document.body;a=c.top+("pageYOffset"in window?window.pageYOffset:(document.documentElement||f.parentNode||f).scrollTop);c=c.left+("pageXOffset"in window?window.pageXOffset:(document.documentElement||f.parentNode||f).scrollLeft);f=a.toString()+","+c;b.b.hasOwnProperty(f)?a=!1:(b.b[f]=!0,a=a<=b.e.height&&c<=b.e.width)}a&&(b.a.push(e),b.d[e]=!0)};p.prototype.checkImageForCriticality=function(b){b.getBoundingClientRect&&q(this,b)};h("pagespeed.CriticalImages.checkImageForCriticality",function(b){n.checkImageForCriticality(b)});h("pagespeed.CriticalImages.checkCriticalImages",function(){r(n)});var r=function(b){b.b={};for(var d=["IMG","INPUT"],a=[],c=0;c<d.length;++c)a=a.concat(l(document.getElementsByTagName(d[c])));if(0!=a.length&&a[0].getBoundingClientRect){for(c=0;d=a[c];++c)q(b,d);a="oh="+b.i;b.c&&(a+="&n="+b.c);if(d=0!=b.a.length)for(a+="&ci="+encodeURIComponent(b.a[0]),c=1;c<b.a.length;++c){var e=","+encodeURIComponent(b.a[c]);131072>=a.length+e.length&&(a+=e)}b.g&&(e="&rd="+encodeURIComponent(JSON.stringify(s())),131072>=a.length+e.length&&(a+=e),d=!0);t=a;if(d){c=b.f;b=b.h;var f;if(window.XMLHttpRequest)f=new XMLHttpRequest;else if(window.ActiveXObject)try{f=new ActiveXObject("Msxml2.XMLHTTP")}catch(k){try{f=new ActiveXObject("Microsoft.XMLHTTP")}catch(u){}}f&&(f.open("POST",c+(-1==c.indexOf("?")?"?":"&")+"url="+encodeURIComponent(b)),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.send(a))}}},s=function(){var b={},d=document.getElementsByTagName("IMG");if(0==d.length)return{};var a=d[0];if(!("naturalWidth"in a&&"naturalHeight"in a))return{};for(var c=0;a=d[c];++c){var e=a.getAttribute("pagespeed_url_hash");e&&(!(e in b)&&0<a.width&&0<a.height&&0<a.naturalWidth&&0<a.naturalHeight||e in b&&a.width>=b[e].k&&a.height>=b[e].j)&&(b[e]={rw:a.width,rh:a.height,ow:a.naturalWidth,oh:a.naturalHeight})}return b},t="";h("pagespeed.CriticalImages.getBeaconData",function(){return t});h("pagespeed.CriticalImages.Run",function(b,d,a,c,e,f){var k=new p(b,d,a,e,f);n=k;c&&m(function(){window.setTimeout(function(){r(k)},0)})});})();pagespeed.CriticalImages.Run('/mod_pagespeed_beacon','https://censored.com/CDash/index.php?project=VTK+Nightly','YddRYU7ik1',true,false,'vYaXqC0QJN0');
//]]></script><img src="img/settings.png" pagespeed_url_hash="2621796496" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"/>

```
 
Does anyone have any idea what's going on here? Why is this dodgy javascript intermittently ruining the dashboard? The dashboard is not fit to be on public display while it's in this state :-(

I have attached screenshots so you can see what I'm talking about also.

Many thanks for any assistance!

Good cdash :
![cdash-good-simple](https://user-images.githubusercontent.com/17421309/33549298-fe070422-d939-11e7-8613-96e460cd6601.JPG)

Bad cdash! :
![cdash-bad](https://user-images.githubusercontent.com/17421309/33549321-08737094-d93a-11e7-8c5a-5f25a03d4d87.JPG)

**Comment by zackgalbreath** [comment]
Hmm, strange.  I've never encountered this behavior before.  It looks like the offending diff is coming from `mod_pagespeed`?  More details here: https://stackoverflow.com/a/33103980

**Comment by SupremeGit** [comment]
Thanks Zack, 

that was the tip I needed. If this pagespeed business isn't usually used with cdash, then it has no business being there. So i've disabled it for my CDash URLs, and the problem is fixed!

For anyone else, this problem arose after installing CDash on a bitnami EC2 wordpress instance, so the apache has been setup to suit wordpress, and the pagespeed module is probably very useful for that. But it can be disabled for particular url wildcards so I've done that for URLs containing CDash, and now my CDash is all good and wordpress should be unaffected.

Thanks again!
John

**Comment by SupremeGit** [comment]
All is good. Issue fixed by disabling mod_pagespeed for CDash URLs.
