### ISSUE TITLE
CDash main pages do not list results

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#638]
Starting Friday, the main page of the Slicer dashboard stopped reporting results (despite of being submitted).

See http://slicer.cdash.org/index.php?project=Slicer4

**Comment by jcfr** [comment]
As reported by @dzenanz, Issue is not limited to Slicer, ITK dashboard are also missing: https://open.cdash.org/index.php?project=Insight

Cc: @thewtex @fbudin69500

**Comment by zackgalbreath** [comment]
Thanks for the heads up @jcfr.  The version of PHP installed on cdash.org was slightly older than we expected.  This issue is fixed now. We're gradually chewing through the backlog of XML files.

**Comment by jcfr** [comment]
Thanks for the update. I confirm that [yesterday](http://slicer.cdash.org/index.php?project=Slicer4&date=2018-02-11) results have been processed and are now visible.
