### ISSUE TITLE
Admin actions ineffective and lost of login

### ISSUE THREAD

**Issue by sjoubert** [Kitware/CDash#642]
Hi, 

I have some issues on my own instance of CDash (I'm using prebuilt_1e075408b6395bc97611b4d1845c8173fef32c37). None of the admin users can perform administration action.

Repro steps:
1. Log in with an admin account
1. Go to a project configuration page to add a user to it: it asks for login, I think in earlier versions it did not require a second login for administration actions
1. Login
1. Choose a user and click 'add user'
1. Login is prompted again and after login again the user is not in the project (you can repeat that again and again with no effect)

In addition, every user (admin or not) loose their session after some time (like around 30min or 1hour) even with the appropriate checkbox "remember me" used.

I've checked the CDash logs, nothing stands out. However, the following line appears a lot in the apache log:
`[Tue Feb 27 12:02:25.729407 2018] [:error] [pid 1423] [client XXX.XXX.XXX.XXX:PPPPP] PHP Notice:  Undefined variable: storedPassword in <CDash_DIR>/include/login_functions.php on line 220, referer: https://cdash.url/user.php`

I don't know if all these behaviors (admin actions, lost of login and apache error) are related.

Anyway, not being able to administrate the CDash instance and having to reconnect every hour makes it almost unusable.

Thanks

**Comment by zackgalbreath** [comment]
Sorry for the slow reply.

I just attempted to reproduce this on the same prebuilt version and it worked fine for me. So I think your hunch might be correct that this is a bug with our LDAP authentication. I'll work on getting that set up locally & report back.

**Comment by zackgalbreath** [comment]
Hmm, I still can't reproduce this after switching my authentication to LDAP. I did notice an undefined variable warning though.  I doubt that's what's causing your problem, but you could try merging this fix to see if it helps. https://github.com/Kitware/CDash/pull/651

Just to make sure we're trying to same thing, you're using manageProjectRoles.php to add users to your project, right?

**Comment by sjoubert** [comment]
Yes, you're correct I'm using manageProjectRoles.php but I also encountered the issue on manageBanner, manageCoverage, but *not* on the other entries of the Settings menu appart from manageOverview which seems even more broken showing at the same time both the login form and the overview edition forms:
![manageoverview](https://user-images.githubusercontent.com/200310/37393430-5b470e4a-2771-11e8-9318-b9244b2650f7.png)

Anyway, I've applied #651 and the admin actions no longer require additional login and have the expected effect. Thanks for this fix!

However, I still loose the login/session regularly even with "Remember Me" checked at login.

**Comment by sjoubert** [comment]
Well, I checked my server config (config/config.local.php) and found out that the `CDASH_COOKIE_EXPIRATION_TIME` variable was set to `3600` which could have explained the ~1h timeout on the login.

I've set it to `43200` (12h), reboot the server, checked that the session cookie (on my local browser) had a correct new expiration time but unfortunately the ~1h timeout did not disappear :-(

**Comment by bryonbean** [comment]
Just so happens that I'm working on encapsulating the Session information for CDash. I do know that there are currently two session cookies being set, one that is the result of "remember me" and the other the general purpose session cookie. Not sure if they're both being handled properly but it sounds as if one of the cookies is not correctly using the configured expiration time. I'll take a look into this over the weekend. In the mean time do you see the "remember me" cookie being set in your browser? It's named differently from the general purpose cookie, that is, it is named `'CDash-' . $_SERVER['SERVER_NAME']`, so in my case the cookie would simply be name _CDash-localhost_.

**Comment by sjoubert** [comment]
I do see both of them:
* The "normal" one with the 12h expire time I've set in the config
* The "remember me" one with ~1month expire time

The content of these cookies are not equal. I could not relate the "normal" one to anything in the server database. However, the content of the "remember me" cookie is exactly `8<cookie_key_as_found_in_the_db_user_table>`

Hope this can help.

**Comment by williamjallen** [comment]
CDash has evolved significantly since this issue was posted.  If you continue to experience problems, please open a new issue.
