### ISSUE TITLE
Docker Release version

### ISSUE THREAD

**Issue by mv740** [Kitware/CDash#653]
Hi, 

I found this [cdash docker](https://gitlab.kitware.com/bryonbean/cdash-docker) but it is for testing and development. 

Can we have a much more simple one without all the different libraries requires for developments?.

**Comment by bryonbean** [comment]
@bradking wanted to ping you on this with regard to our conversation for setting up a Kitware account at hub.docker.com. (see https://hub.docker.com/r/bbeanatkitware/cdash-host/)

**Comment by mv740** [comment]
thanks! I wasn't sure if that image was build from that repo since there wasn't any information in the Info Repo tab.

**Comment by bryonbean** [comment]
@mv740 This is the image that we use to test CDash with so it comes with all of the necessary libraries to do so. There is not currently an image without these libraries and I'm not sure when we'll get around to creating one but it does seem like having one would be advantageous.

**Comment by zackgalbreath** [comment]
We are now automatically deploying an image to DockerHub whenever there is a clean merge to master.

https://hub.docker.com/r/kitware/cdash/
