### ISSUE TITLE
testDetails page fails to render

### ISSUE THREAD

**Issue by roowatt** [Kitware/CDash#656]
When running latest prebuilt branch without any repo or repository viewer I see the following error in the webserver log.

[Tue Mar 27 15:40:00.648286 2018] [php7:error] [pid 27715] [client 192.168.1.120:62965] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function get_viewcvs_revision_url(), 2 passed in /opt/CDash/include/repository.php on line 668 and exactly 3 expected in /opt/CDash/include/repository.php:511\nStack trace:\n#0 /opt/CDash/include/repository.php(668): get_viewcvs_revision_url('', NULL)\n#1 /opt/CDash/public/api/v1/testDetails.php(215): get_revision_url('1', NULL, NULL)\n#2 {main}\n  thrown in /opt/CDash/include/repository.php on line 511, referer: http://192.168.1.140/cdash/testDetails.php?test=1&build=1

After poking  around a bit, I found that the attached patch resolved the issue. Not usre if it is the correct or best fix but at least now I can see the submitted test log.
[cdash.diff.txt](https://github.com/Kitware/CDash/files/1850475/cdash.diff.txt)

**Comment by mv740** [comment]
I got the same problem, after adding a random address in the Repository Viewer URL, I could see my test details page correctly!

**Comment by zackgalbreath** [comment]
Thanks for noticing this.  I applied the fix you suggested and updated the prebuilt branch.  Feel free to reopen if this is still an issue for you.
