### ISSUE TITLE
I dont recieve the recover password email

### ISSUE THREAD

**Issue by mehdi-goli** [Kitware/CDash#672]
I am seeing this on top of my browser : A confirmation message has been sent to your inbox.
But I don't receive any email.

**Comment by zackgalbreath** [comment]
What CDash instance is this for?

**Comment by KineticTheory** [comment]
When requesting password recovery via https://xxx.xxx.com/cdash3/recoverPassword.php, I see two behaviors:
* If I enter a bogus email address, CDash responds with `A confirmation message has been sent to your inbox.`.  I'm fine with this behavior.
* If I enter a valid email address for my cdash account, I'm getting `500 Server Error`

This is for self-hosted CDash v3.0.2-1-g61ef950f2.

**Comment by zackgalbreath** [comment]
Thanks for letting us know. I agree that this sounds like a bug. I'll take a closer look locally.

**Comment by zackgalbreath** [comment]
I see. The trick is to run:

`php artisan config:migrate`

 to automatically copy your config settings from `config.local.php`  to `.env`.

More details here:
https://github.com/Kitware/CDash/blob/master/docs/install.md#configure-cdash-and-generate-build-files

I tried this locally and it seems like it's doing the right thing.

Closing for now as I don't see anything to fix. Feel free to reopen if you continue to have trouble with email config.
