### ISSUE TITLE
Command line not visible on paraview dashboard

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#690]
Looking at this failing test: https://open.cdash.org/testDetails.php?test=663368074&build=5419630

The command line is not reported:

![image](https://user-images.githubusercontent.com/219043/41473508-81145a88-7087-11e8-8c5d-5cdd30a4b4bb.png)

Test is added [here](https://github.com/Kitware/ParaView/blob/6324cb611769106b66cbb85d16dac17eee16f050/Plugins/GMVReader/Testing/CMakeLists.txt#L23-L27) using ` add_client_server_tests`

Implementation of ` add_client_server_tests` function can be found [here](https://github.com/Kitware/ParaView/blob/5b6a27377e9bc3377d72d61a57ee745412d39429/CMake/ParaViewTestingMacros.cmake#L297-L310) and [here](https://github.com/Kitware/ParaView/blob/5b6a27377e9bc3377d72d61a57ee745412d39429/CMake/ParaViewTestingMacros.cmake#L132-L199)

Cc: @cquammen

**Comment by zackgalbreath** [comment]
The fix for this has been deployed on open.cdash.org.  Please feel free to re-open this issue if the problem crops up again.

**Comment by jcfr** [comment]
Great, looking at a [recent submission](https://open.cdash.org/testDetails.php?test=681404837&build=5510077), command line is reported:

![image](https://user-images.githubusercontent.com/219043/44598275-67a0d680-a7a0-11e8-83c5-a8efdf40aca0.png)

:+1:
