### ISSUE TITLE
Can't view test log

### ISSUE THREAD

**Issue by mv740** [Kitware/CDash#699]
Hi

I  was testing my latest changes, but I'm getting this weird errors when I'm trying to access my test log

Is this because my log file is too big ? 

angular.js:14328 TypeError: Cannot use 'in' operator to search for 'redirect' in 
    at Object.initialRender (.../js/CDash_2.5.0.min.js:85:111)
    at .../js/CDash_2.5.0.min.js:98:233
    at processQueue (../js/CDash_2.5.0.min.js:44:7417)
    at .../js/CDash_2.5.0.min.js:44:8255
    at Scope.$eval (.../js/CDash_2.5.0.min.js:44:21346)
    at Scope.$digest (.../js/CDash_2.5.0.min.js:44:19005)
    at Scope.$apply (.../js/CDash_2.5.0.min.js:44:21772)
    at done (.../js/CDash_2.5.0.min.js:43:8146)
    at completeRequest (.../js/CDash_2.5.0.min.js:43:12603)
    at XMLHttpRequest.xhr.onload (.../js/CDash_2.5.0.min.js:43:13341) Possibly unhandled rejection: {}

**Comment by zackgalbreath** [comment]
Which CDash site is this for?  Can you share a link to your project here?

**Comment by mv740** [comment]
It's my workplace's internal CDash, so I can't, 

here some extra debug info : 
![image](https://user-images.githubusercontent.com/1993293/43213219-1a3ae060-9004-11e8-80bf-668101b82ffd.png)

![image](https://user-images.githubusercontent.com/1993293/43213286-420ce50c-9004-11e8-904f-4e335b65d164.png)

variable cdash is empty...

**Comment by mv740** [comment]
if I do api/v1/testDetails.php?test=1&build=1 I get nothing ...

I tried "/api/v1/testDetails.php?test=1"   remove the build id, I get "This build doesn't exist."

**Comment by mv740** [comment]
under  Test : 

![image](https://user-images.githubusercontent.com/1993293/43214291-dc439088-9006-11e8-88e5-171f2c6927b9.png)

**Comment by zackgalbreath** [comment]
Sounds like something's going wrong on the server when trying to retrieve this test data.  Can we check the PHP error logs for more clues?  If you're running an apache2 web server these are often logged to `/var/log/apache2/error.log` by default.

**Comment by mv740** [comment]
I am not getting any errors in my log... 

I think I will wait for your guys to merge #698 and I will test your latest version, to see if I am capable of reproducing my bug
