### ISSUE TITLE
Special handling of terminal control characters

### ISSUE THREAD

**Issue by zachmullen** [Kitware/CDash#70]
They currently render as CTest sends them, e.g. 

```
[NON-XML-CHAR-0x1B][31mCreate a data hierarchy: 42 of 46 passed.[NON-XML-CHAR-0x1B][0m
```

We should transform that special string `[NON-XML-CHAR-0x1B]` into its appropriate UTF8 value and use some existing javascript library to render the text in the appropriate style as it would appear in the terminal.

**Comment by zackgalbreath** [comment]
Fixed by #618 and #625.  Thanks Kyle!
