### ISSUE TITLE
Object is a php7 type

### ISSUE THREAD

**Issue by cryptomilk** [Kitware/CDash#709]
I get the following error running the prebuilt branch:

```
[php7:error] [pid 14968] [client 78.46.80.163:58960] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /srv/www/vhosts/cmocka/test/app/Model/Object.php on line 17
```

The reason is that object is a type by the php language, see:
https://secure.php.net/manual/en/language.types.object.php

It should be renamed to `Obj` or something else, but not `Object` :-)

**Comment by zackgalbreath** [comment]
Thanks for reporting this.

@bryonbean would `Model` be an appropriate replacement name here?

**Comment by bryonbean** [comment]
I think `ModelType` is probably more appropriate. However it looks like the original global it was replacing was called `CDASH_OBJECT_*` if for some historical reason it needs to reflect that.

**Comment by cryptomilk** [comment]
Then either use `ObjectType` or `ModelType`.

**Comment by bryonbean** [comment]
@cryptomilk correct, either one will work. I personally prefer `ModelType` as it seems slightly more descriptive, but that's probably splitting hairs.
