### ISSUE TITLE
The prebuilt branch misses vendor/bernard/bernard/

### ISSUE THREAD

**Issue by cryptomilk** [Kitware/CDash#718]
The prebuilt branch currently doesn't work because vendor/bernard/bernard/ is empty.

Could someone please fix it?

Thanks.

**Comment by zackgalbreath** [comment]
Whoops, this was tricky since Bernard was a git checkout all its own.  This should be fixed now.  Let me know if it still doesn't work right for you.

**Comment by cryptomilk** [comment]
The code tries to load `vendor/bernard/bernard/src/Bernard/functions.php`

however `src/Bernard` doesn't exist ...

```
[Wed Sep 19 10:34:43.778865 2018] [php7:error] [pid 29134] [client 185.17.206.51:13067] PHP Fatal error:  require(): Failed opening required '/srv/www/vhosts/cmocka/test/vendor/composer/../bernard/bernard/src/Bernard/functions.php' (include_path='/srv/www/vhosts/cmocka/test/vendor/pear/pear_exception:/srv/www/vhosts/cmocka/test/vendor/pear/console_getopt:/srv/www/vhosts/cmocka/test/vendor/pear/pear-core-minimal/src:/srv/www/vhosts/cmocka/test/vendor/pear/archive_tar:.:/usr/share/php7:/usr/share/php7/PEAR') in /srv/www/vhosts/cmocka/test/vendor/composer/autoload_real.php on line 70
```

**Comment by cryptomilk** [comment]
You need to use the v0.12.4 tag of Bernard ...

**Comment by zackgalbreath** [comment]
> You need to use the v0.12.4 tag of Bernard

Right you are.  I just updated the `prebuilt` branch again.  Everything looks right to me locally, but as always please let us know if you encounter any difficulties.
