### ISSUE TITLE
Commit hashes treated as integers

### ISSUE THREAD

**Issue by mathstuf** [Kitware/CDash#724]
The update column on [this page](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=ParaView&showfilters=0&limit=100&value1=0689968ef0557fe4add67cd6a088ecd6392e0a96&showfeed=0) is missing the leading `0` of the commit it actually is: `0689968ef0557fe4add67cd6a088ecd6392e0a96` presumably because the remaining characters of the short hash "looks like" an integer. Implicit type conversion somewhere?

**Comment by mathstuf** [comment]
Note that I don't know how long that page will stay valid. Here's a cropped screenshot showing the query value in the URL and the rendering in the Update column.

![cdash-hash-string](https://user-images.githubusercontent.com/97253/46014840-ab884380-c09e-11e8-909a-75a205b3f721.png)

**Comment by zackgalbreath** [comment]
Thanks for pointing this out, Ben.

The background here is that by default all data is returned to us from the database in string format. As you can probably imagine, this causes problems eg. for sorting.  So we [do our best](https://github.com/Kitware/CDash/blob/master/include/common.php#L2044) to detect what type of data is held by each variable and cast it appropriately.

The only place we've run into a problem with this strategy so far is checksums (git commits).  #493 previously attempted to deal with this problem, but apparently it was inadequate.  Instead we'll need some mechanism to say "no really, this should be a string".

**Comment by zackgalbreath** [comment]
Fixed in #1009
