### ISSUE TITLE
Syntax error in common.php? (trilinos-release-2018-08-prebuilt)

### ISSUE THREAD

**Issue by KineticTheory** [Kitware/CDash#725]
We tried to install the release 'trilinos-release-2018-08-prebuilt' today but encountered the error:

```
[Fri Sep 21 09:17:55.739817 2018] [:error] [pid 69768] [client 128.165.87.67:56044] PHP Parse error:  
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or 
'{' or '$' in /var/www/virtual/xxx.lanl.gov/html/CDash-trilinos-release-2018-08-prebuilt/include/common.php on line 1928
```

Do you have any suggestions for fixing this issue?

I pulled down today's version of `common.php` but that script had other issues.  What are the recommended installation instructions for running something newer than version 2.4?

**Comment by zackgalbreath** [comment]
CDash now requires that you're running PHP 5.6 or newer.  It looks like you must be using a version of PHP older than 5.5.0 since it doesn't recognize the `::class` syntax used on this line.

**Comment by KineticTheory** [comment]
@zackgalbreath Thanks for the quick response.  

We are stuck with using *RHEL 7.5 (Maipo)* and RH only provides PHP 5.5.  I guess that means we are stuck using an older version of CDash.  We are trying to install CDash 2.4 now.
