### ISSUE TITLE
Submit to CDash Upload API causes "Not a valid project." upload response error on a valid project

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#736]
I have a ctest script that can be summed up to 
~~~
CTEST_START(Experimental)
CTEST_CONFIGURE()
CTEST_BUILD()
CTEST_TEST()
CTEST_COVERAGE()
CTEST_SUBMIT()
INCLUDE(CTestCoverageCollectGCOV.cmake)
CTEST_COVERAGE_COLLECT_GCOV(TARBALL gcov.tar)
IF(EXISTS "gcov.tar")
    CTEST_SUBMIT(CDASH_UPLOAD "gcov.tar" CDASH_UPLOAD_TYPE GcovTar)
ENDIF()
~~~

Although the first ctest_submit() succeeds, the same configuration causes a failure for the second one (CDASH_UPLOAD) with the following message:

~~~
Request upload response: [<cdash version="2.2.3">
 <status>ERROR</status>
 <message>Not a valid project.</message>
</cdash>
]
~~~

Am I doing something wrong or might there be a bug somewhere?
Thanks a lot!

**Comment by zackgalbreath** [comment]
CDash 2.2.3 is probably too old to understand the `ctest_submit(CDASH_UPLOAD)` signature.  Is this for my.cdash.org?  If so, we're hoping to finally upgrade that instance in the coming weeks.

**Comment by vlebourl** [comment]
Thanks for the answer! It's a private cdash server, we'll upload tomorrow. The error message is quite misleading though, and the documentation on the ctest_submit page quite scarce. For instance, it's rather difficult to find the correct <type> to put in the CDASH_UPLOAD_TYPE.
