### ISSUE TITLE
Support  `/api/v1/` authentication call through API login endpoint

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#743]
Current it is required to have session, see `get_userid_from_session` in [include/api_common.php](https://github.com/Kitware/CDash/blob/95ae4837fbe30a73b7bb2352c2470a82e55f5e77/include/api_common.php#L52-L78), it would be easier to have a login end point supporting API token.

**Comment by jcfr** [comment]
Look like there is a Web API key

![image](https://user-images.githubusercontent.com/219043/47262178-86290280-d4af-11e8-9f58-4e0a79111cdf.png)

But not sure yet how to create it ... 

![image](https://user-images.githubusercontent.com/219043/47262184-a8bb1b80-d4af-11e8-98ff-6e78195f4bd2.png)

**Comment by jcfr** [comment]
Based on the Login old API documentation .. a value should be displayed there: https://public.kitware.com/Wiki/CDash:API#Login

**Comment by jcfr** [comment]
I was able to create a token using the following URL after login through the web interface: http://slicer.cdash.org/api/v1/authtoken.php?description=Slicer

**Comment by jcfr** [comment]
To list the token, one can use the following URL: http://slicer.cdash.org/api/v1/user.php

**Comment by jcfr** [comment]
And it turns out that the API was on the user profile at the bottom:

![image](https://user-images.githubusercontent.com/219043/47262288-ad350380-d4b2-11e8-83ee-0e6576e38e71.png)

**Comment by jcfr** [comment]
I will update the wiki page accordingly.

**Comment by zackgalbreath** [comment]
Glad you figured this out.  Thanks for updating the documentation!
