### ISSUE TITLE
Autentication Tokens section not visible by default

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#744]
The Authentication Tokens appear only after creating at least on token using the `api/v1/authtoken.php` end point (e.g http://slicer.cdash.org/api/v1/authtoken.php?description=Slicer)

![image](https://user-images.githubusercontent.com/219043/47262698-95af4800-d4bd-11e8-8759-a55825f5b989.png)

Look like the `cdash.showauthtokens` test should simply be removed.

https://github.com/Kitware/CDash/blob/95ae4837fbe30a73b7bb2352c2470a82e55f5e77/public/views/user.html#L284-L286

**Comment by jcfr** [comment]
Look like at least one project need to have the `authenticatesubmissions` evaluate to true

https://github.com/Kitware/CDash/blob/95ae4837fbe30a73b7bb2352c2470a82e55f5e77/public/api/v1/user.php#L93-L95

**Comment by zackgalbreath** [comment]
Good call.  Originally these auth tokens were only used for authenticated submissions, but as you discovered they are also useful for accessing protected API endpoints.  For this reason, we should unconditionally show this section on `user.php`.

**Comment by zackgalbreath** [comment]
Fixed in #757
