### ISSUE TITLE
Document how to use via Docker

### ISSUE THREAD

**Issue by estan** [Kitware/CDash#746]
It would be great if usage via Docker/docker-compose was documented.

Wouldn't have to be much, just an offical quick start sort of thing.

Sorry if there is one and I've missed it.

BTW, we're running from the old 2.4.0-prebuilt release package, but I have it on my TODO to look into upgrading to something more recent. What is the recommended way of using a more modern CDash? The master branch, the prebuilt branch? Any idea when the next release might be due?

**Comment by zackgalbreath** [comment]
https://github.com/Kitware/CDash/blob/master/docker.md

Please feel free to reopen this issue (or open a new one) if this documentation seems unclear or incomplete to you.
