### ISSUE TITLE
Repository Viewer URL not remembering https

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#749]
Although I add an httpS address on the viewer url in the repository tab of the project setup, updating project and reloading the page rolls back the url to an http version.

**Comment by zackgalbreath** [comment]
No worries.  We're going to release CDash 2.6 next week.  Once that's out you can upgrade at your convenience and we'll check if this is still an issue for you or not.

**Comment by vlebourl** [comment]
same as for #762...
