### ISSUE TITLE
Clicking on the calendar tab takes you to "unsafe:javascript:;"

### ISSUE THREAD

**Issue by umar456** [Kitware/CDash#759]
Clicking on the calendar tab in the project page takes you to the "unsafe:javascript:;" URL

**Comment by zackgalbreath** [comment]
Which PHP page in CDash is causing this issue for you? On index.php the link goes to `javascript:;` for me and clicking on it correctly displays the calendar widget.

**Comment by umar456** [comment]
I am seeing this on the index.php page. I am using Firefox 62 if that helps. Here is the link of the instance: http://ci.arrayfire.org/index.php?project=ArrayFire

**Comment by zackgalbreath** [comment]
Fixed in #761
