### ISSUE TITLE
SVN not recognized as a VCS with revision

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#762]
Hi, 
We use SVN as our vcs for our project.
I saw that a much wanted feature in our personal CDash install was actually already committed (https://github.com/Kitware/CDash/pull/485/commits), but yet the update column in our CDash shows the number of files updated rather than the svn revision number...
Any chance there's an option we haven't activated?
Thanks a lot.

Here is an example of an Update.xml submitted by our ctest script:

~~~
<?xml version="1.0" encoding="UTF-8"?>
<Update mode="Client" Generator="ctest-3.13.20181018-gaab69c">
	<Site>MacOS10.13-Folsomia</Site>
	<BuildName>x64-clang-Debug-TestCalc</BuildName>
	<BuildStamp>20181101-0845-Experimental</BuildStamp>
	<StartDateTime>Nov 01 09:45 CET</StartDateTime>
	<StartTime>1541061907</StartTime>
	<UpdateCommand>"svn" "update" "--non-interactive"</UpdateCommand>
	<UpdateType>SVN</UpdateType>
	<Revision>12413</Revision>
	<SVNPath>/</SVNPath>
	<Directory>
		<Name>Config/CMake</Name>
		<Modified>
			<File>CMakeLists.txt</File>
			<Directory>Config/CMake</Directory>
			<FullName>Config/CMake/CMakeLists.txt</FullName>
			<CheckinDate>Unknown</CheckinDate>
			<Author>Unknown</Author>
			<Email></Email>
			<Committer></Committer>
			<CommitterEmail></CommitterEmail>
			<CommitDate></CommitDate>
			<Log></Log>
			<Revision>Unknown</Revision>
			<PriorRevision>12413</PriorRevision>
		</Modified>
	</Directory>
	<EndDateTime>Nov 01 09:45 CET</EndDateTime>
	<EndTime>1541061908</EndTime>
	<ElapsedMinutes>0</ElapsedMinutes>
	<UpdateReturnStatus>Update error: There are modified or conflicting files in the repository</UpdateReturnStatus>
</Update>
~~~

Actual result:

<img width="588" alt="actual" src="https://user-images.githubusercontent.com/5701372/47843285-6bb02c80-ddbf-11e8-9eca-b694baa133ee.png">

Expected result:

<img width="591" alt="expected" src="https://user-images.githubusercontent.com/5701372/47843286-6bb02c80-ddbf-11e8-8879-9e32dec5a3e4.png">

**Comment by vlebourl** [comment]
It appears I'm actually running tag 2.4.0-prebuild which is a very old (2016) release... Which tag / branch is the best to use if we want to be on a recent yet stable version of CDash? And how can we know if the database model has been modified?

**Comment by vlebourl** [comment]
Any answer? And what about CDash 2.6 (cf https://github.com/Kitware/CDash/issues/749#issuecomment-433394201)?

**Comment by zackgalbreath** [comment]
> Which tag / branch is the best to use if we want to be on a recent yet stable version of CDash? 

I recommend the prebuilt branch if you want recent-yet-stable.  If that seems too ambitious to you, d127922 looks like the oldest prebuilt commit that provides the feature you're interested in.  So if you want a minimal set of changes while still getting Revision numbers in the update column, that might be a good way to go.


> how can we know if the database model has been modified?

After upgrading, CDash will show a notice on `viewProjects.php` if your database schema is not up-to-date.
![database_schema_notice](https://user-images.githubusercontent.com/224720/48152698-95bb9000-e292-11e8-8aca-8019c4860d78.png)

Given two revisions you're interested in (eg `HEAD` and `prebuilt`) you can use the following command to see if the database schema has changed between them.
```
$ git diff HEAD..prebuilt sql/mysql/cdash.sql
```


> And what about CDash 2.6?

There's been a couple bug fixes that we wanted to get into master first, but we're still planning to cut this release ASAP.

**Comment by vlebourl** [comment]
thanks a lot for the detailed answer 👍
