### ISSUE TITLE
CDash fails to parse Configure.xml

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#769]
Although the Configure.xml file submitted to CDash contains loads of information (see below), CDash doesn't show any of it in the view:
![image](https://user-images.githubusercontent.com/5701372/48561189-bcf80a00-e8ef-11e8-9192-7a530a03f2c7.png)

Any idea?

Configure.xml:
~~~
<Configure>
		<StartDateTime>Nov 15 15:52 CET</StartDateTime>
		<StartConfigureTime>1542293523</StartConfigureTime>
		<ConfigureCommand>cmake .. -G 'Ninja'     -DCMAKE_CXX_COMPILER:FILEPATH=/usr/local/bin/clang++     -DCMAKE_C_COMPILER:FILEPATH=/usr/local/bin/clang     -DCMAKE_AR:FILEPATH=/usr/local/bin/llvm-ar     -DCMAKE_NM:FILEPATH=/usr/local/bin/llvm-nm     -DCMAKE_RANLIB:FILEPATH=/usr/local/bin/llvm-ranlib</ConfigureCommand>
		<Log>-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vlb/StarQube/Config/CMake/Build
</Log>
		<ConfigureStatus>0</ConfigureStatus>
		<EndDateTime>Nov 15 15:52 CET</EndDateTime>
		<EndConfigureTime>1542293525</EndConfigureTime>
		<ElapsedMinutes>0</ElapsedMinutes>
	</Configure>
~~~

**Comment by zackgalbreath** [comment]
First I would check the API endpoint to see if the configure output is showing up in the JSON data.  My hunch is that it probably isn't.

If the page you're looking at is
  https://mydomain.com/CDash/viewConfigure.php?buildid=123
Then you can go to:
  https://mydomain.com/CDash/api/v1/viewConfigure.php?buildid=123
To see the raw JSON that's used to render the page.

The name of the field in question is `output`.

Assuming that doesn't offer any useful clues, the next thing I would try is checking the database to see if the information is getting in there or not.

```
SELECT log FROM configure
JOIN build2configure ON build2configure.configureid = configure.id
WHERE build2configure.buildid = 123;
```

If there's still no data showing up, it's time to resubmit the `Configure.xml` file and keep an eye on your log files for more clues on what might be going wrong.  This can be a little tricky since CDash, PHP, and MySQL also potentially maintain separate logs.

**Comment by vlebourl** [comment]
It seems that the table build2configure does not exist... Any chance that my cause the behavior? Any way to fix this?

Attached is the list of available tables from:
~~~
SELECT table_schema,table_name
FROM information_schema.tables
ORDER BY table_schema,table_name;
~~~

[CDashDB.log](https://github.com/Kitware/CDash/files/2594829/CDashDB.log)

**Comment by vlebourl** [comment]
We fixed our problem. 

First thing was hitting the `Upgrade CDash` button in the Maintenance panel which didn't change any thing... 

Second one was to manually create the missing databases by applying file from https://github.com/Kitware/CDash/blob/prebuilt/sql/pgsql/cdash-upgrade-2.0-2.6.sql
which solved our problem. 

It seems to me that the upgrade cdash button did not know the correct patch to apply or something like that... Although the file is called "2.0-2.6", our version (applied last week from branch prebuilt) is still on 2.5... Any reason for that?

Thanks in advance!!

(by the way, great reactivity and great answers to my different posts! congrats)

**Comment by zackgalbreath** [comment]
> First thing was hitting the `Upgrade CDash` button in the Maintenance panel which didn't change any thing...

Aha, you were hit by this bug:

https://github.com/Kitware/CDash/pull/740

If you cherry-pick that commit onto your branch the `Upgrade CDash` button will function as intended. Or you can wait for CDash 2.6 which is coming out Real Soon Now.
