### ISSUE TITLE
Incorrect integer value: '' for column 'public' at row 1 creating new project on new CDash instance

### ISSUE THREAD

**Issue by timbrown5** [Kitware/CDash#784]
This is a new cdash server deployed using the docker image: https://github.com/Kitware/cdash-docker
I have connected to a new mysql (5.7.23) database and followed the step on /install.php

The error is:
```
cdash.ERROR: Incorrect integer value: '' for column 'public' at row 1
{
    "function": "pdo_error",
    "pid": 72
}
```

**Comment by timbrown5** [comment]
Ok, I can fix/workaround this by ticking the 'Public dashboard' option on the 'Information' page.

**Comment by zackgalbreath** [comment]
Thanks for letting us know, we'll look into it.

**Comment by williamjallen** [comment]
This appears to be working as of the latest version of master.  If you continue to experience issues with the latest version of CDash, please open a new issue.
