### ISSUE TITLE
Upgrade from 1.4.2 to 2.6.0 issue

### ISSUE THREAD

**Issue by dfranco** [Kitware/CDash#789]
Hello,

Trying to upgrade CDash from version 1.4.2 to 2.6.0 fail with the following error in log/cdash.log

`cdash.ERROR: Specified key was too long; max key length is 767 bytes {"function":"pdo_error","pid":XXXX}`

The system running the upgrade is Debian 9 (stretch) with PHP 7.0.33 and MariaDB 10.1

Any help would be nice

**Comment by bast** [comment]
I ran into the same problem (same system) and followed this advice: http://blog.antiblau.de/tag/cdash/ which solved this for me.

More specifically, I did this before visiting `install.php`:
```mysql
CREATE DATABASE cdash CHARACTER SET utf8 COLLATE utf8_general_ci;
```
