### ISSUE TITLE
Feed::GetFeed(): 0 not set

### ISSUE THREAD

**Issue by juraj67** [Kitware/CDash#798]
Hello,

After creating a new CDash project on localhost, I can not open this project and the CDash returns an error:
**Feed::GetFeed(): 0 not set**

Thanks in advance for your help.

**Comment by zackgalbreath** [comment]
assuming your project is at

http://localhost/CDash/index.php?project=MyProject

do you get valid JSON if you go to 

http://localhost/CDash/api/v1/index.php?project=MyProject

?

**Comment by juraj67** [comment]
I get this output when visiting second link:
> 
**Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/ects/srcBuild/CDash/include/filterdataFunctions.php on line 1272**
{"version":"2.6.0","feed_enabled":true,"user":{"admin":1,"id":1},"header":"views\/partials\/header.html","footer":"views\/partials\/footer.html","title":"CDash - BranchCoverageExample","showcalendar":1,"banners":[],"parentid":-1,"datetime":"Tuesday, February 19 2019 08:22:59","date":"2019-02-19","unixtimestamp":1550538000,"startdate":"Tuesday, February 19 2019 01:00:00","vcs":"http:\/\/","bugtracker":"http:\/\/","googletracker":"","documentation":"http:\/\/","projectid":1,"projectname":"BranchCoverageExample","projectname_encoded":"BranchCoverageExample","public":0,"previousdate":"2019-02-18","nextdate":"2019-02-20","logoid":0,"home":"index.php?project=BranchCoverageExample","projectrole":2,"displaylabels":0,"showtesttime":0,"childview":0,"menu":{"nonext":1},"filterdata":{"hasdateclause":0,"pageId":"index.php","pageSpecificFilters":{"TextConcat":"GROUP_CONCAT(text SEPARATOR ', ')","HasSubProjectsFilter":false,"FiltersAffectedBySubProjects":["buildduration","builderrors","buildwarnings","configureduration","configureerrors","configurewarnings","testsduration","testsfailed","testsnotrun","testspassed","testtimestatus"]},"debug":0,"filtercombine":"","filters":[{"field":"site","fieldtype":"string","compare":63,"value":""}],"limit":0,"showfilters":0,"colorblind":0,"showlimit":1,"sql":""},"filterurl":"","coverages":[],"dynamicanalyses":[],"comparecoverage":0,"all_buildgroups":[{"id":1,"name":"Nightly"},{"id":2,"name":"Continuous"},{"id":3,"name":"Experimental"}],"showorder":false,"showstarttime":true,"showProcTime":false,"buildgroups":[],"enableTestTiming":0,"generationtime":0.0109999999999999993616217608405349892564117908477783203125}

Any further recommendations ?

**Comment by zackgalbreath** [comment]
That warning is causing the API endpoint to return invalid JSON, which is breaking the display of index.php. What PHP version are you running? Regardless, we should be able to easily fix this in CDash master.

In the meantime, I think this is caused because you have the PHP `display_errors` directive enabled. To fix this locally:
* edit your php.ini file and set `display_errors = Off`
* restart your web server

**Comment by juraj67** [comment]
My PHP version is 7.2
Your advice was helpful and solved a problem, thank you very much
