### ISSUE TITLE
Branch  coverage percentage

### ISSUE THREAD

**Issue by juraj67** [Kitware/CDash#800]
Hello,

I tried to get branch coverage results of tests from simple program but I realised there is only 1 column in the code output signalising if the branch passed or not (e.g. 1/2 or 2/2).
Is there any way to get branch coverage percentage for the whole code/file/project ? 

Thanks in advance for your help.

**Comment by zackgalbreath** [comment]
You're right, this information should be displayed on the "Coverage Summary" table of viewCoverage.php but currently it is not.

**Comment by juraj67** [comment]
I added columns for gcov branch coverage, are you willing to make change like this ? (For now  I can't get colors working correctly in branch coverage, they are still green). 

This is just example how it should look like:
![cdash1](https://user-images.githubusercontent.com/47740276/54107040-4fa94100-43d8-11e9-81bc-36b121e6847e.PNG)

I would like to hear your opinion.

**Comment by zackgalbreath** [comment]
Sounds good to me. I'd like to make these two new columns only appear when branch coverage data is available. I'd be happy to help with this part if it's not obvious how to do so.

**Comment by juraj67** [comment]
I tried it, but circleci test failed, can you check it please ?
