### ISSUE TITLE
Adiition of 10 in getviewcoverage.php

### ISSUE THREAD

**Issue by juraj67** [Kitware/CDash#807]
Hi,
I would like to ask, why is in "getviewcoverage.php" on line 327 addition of 10.
**Code:**
![code](https://user-images.githubusercontent.com/47740276/54590679-e7d2a600-4a28-11e9-93f3-cba37d788f15.PNG)
I think it is causing that e.g. 0% line coverage is shown as medium coverage, instead of zero coverage.
**With +10:**
![warning](https://user-images.githubusercontent.com/47740276/54590803-36804000-4a29-11e9-9af4-ef9614dd9900.PNG)
**Without +10:**
![zero](https://user-images.githubusercontent.com/47740276/54590809-37b16d00-4a29-11e9-8595-5de15d617e55.PNG)

**Comment by zackgalbreath** [comment]
The purpose of this funny looking math was to de-emphasize small files that are poorly covered. The idea was that if you have a 500 line source file that's only 10% covered, that's more important to fix than a 10 line source file that's only 5% covered.

**Comment by juraj67** [comment]
Thanks for the explanation
