### ISSUE TITLE
Link to the coverage and dynamic analysis sections from buildSummary.php

### ISSUE THREAD

**Issue by reddwarf69** [Kitware/CDash#810]
A single build can generate these:

```
http://<hostname>/buildSummary.php?buildid=88
http://<hostname>/viewCoverage.php?buildid=88
http://<hostname>/viewDynamicAnalysis.php?buildid=88
```

But there isn't a single page grouping all of them. I would argue buildSummary.php is the one that should be linking to viewCoverage.php and viewDynamicAnalysis.php.

As mentioned in https://github.com/Kitware/CDash/pull/748#issuecomment-468663272 it would help seeing the coverage/dynamicAnalysis from GitHub.

Also, how the viewDynamicAnalysis link would look like may depend on how https://github.com/Kitware/CDash/issues/803 is implemented.

**Comment by zackgalbreath** [comment]
You're right, buildSummary.php should link to coverage and dynamic analysis when present.

Even better would be a table of quick-links to the various parts of a build (configure, build errors, tests, etc.) that appears on each of these pages.
