### ISSUE TITLE
Kitware logo huge on Chrome

### ISSUE THREAD

**Issue by cquammen** [Kitware/CDash#815]
The site logo on https://open.cdash.org/ is huge on Chrome Version 71.0.3578.98 (Official Build) (64-bit) on macOS.

Screenshot:
![image](https://user-images.githubusercontent.com/360056/54888383-17dbd800-4e73-11e9-95e1-98a41acaac06.png)

Link to page exhibiting behavior:

https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=ParaView&showfilters=0&limit=100&value1=6d736d2a5cc73a46b36c0948d5299d297652b3e8&showfeed=0

**Comment by cquammen** [comment]
In comparison, the logo is much more reasonable on Safari:

![image](https://user-images.githubusercontent.com/360056/54888454-9cc6f180-4e73-11e9-9a25-459fe91a8079.png)

**Comment by zackgalbreath** [comment]
This is some weird caching issue that I haven't been able to squash yet. If you do a hard refresh it should go away.

**Comment by cquammen** [comment]
Okay, looks like I have a regular size logo now (I didn't get a chance to hard refresh, it just shrank the next time I visited). Sorry for the noise.
