### ISSUE TITLE
Problem showing test failures on open.cdash.org

### ISSUE THREAD

**Issue by cquammen** [Kitware/CDash#819]
When I try to view test failures on ParaView's dashboard, I am brought to a page that says 0 tests failed, even though there are failures reported in the summary table.

To reproduce:
* Go to https://open.cdash.org/index.php?project=ParaView
* Under the "Test" column heading, click on one of the links to test failures.
* It will take you to a page that says there 0 tests failed, even though there were failures reported on the main page.

Expected behavior: the page should report a table of test failures.

**Comment by cquammen** [comment]
I should have noted that links for errors and warnings under Configure and Build headings take you to pages with the expected information. Only links under the Test heading bring you to pages reporting no errors.

**Comment by zackgalbreath** [comment]
Thanks again for letting us know about this problem, Cory. It ended up being due to an upgrade on our MySQL server, which changed the default settings for how GROUP BY` queries can be performed.

**Comment by NixoMoots** [comment]
Hi all, @zackgalbreath : sorry to reopen this post but as I experiment the same behavior on my local installation (CDah 2.6.0), please could you precise the settings for `GROUP BY` you set?

**Comment by zackgalbreath** [comment]
The flag that we had to remove from `sql_mode` was [`ONLY_FULL_GROUP_BY`](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_only_full_group_by).

We also removed `STRICT_TRANS_TABLES` from this list, although I cannot recall at the moment exactly what problem that one was causing.

HTH!

**Comment by NixoMoots** [comment]
It works perfectly, thanks!
About the removal of `STRICT_TRANS_TABLES` we can read in CDash's Wiki  : _"...is that in strict mode, integer columns will not accept the empty string "" as 0 (zero)._"
By the way, the zip file [CDash-2.6.0.zip](https://public.kitware.com/Wiki/CDash:Installation#Stable_Release) from wiki seams to be a `master` not a `preduilt`.
