### ISSUE TITLE
How to use the API Token?

### ISSUE THREAD

**Issue by graslany** [Kitware/CDash#861]
Hello,
I've been using the documentation here to get an API key for a CDash instance. My goal is to list the project and build properties from a Python script, as with the "See as JSON" links at the bottom of html pages.

I tried to follow the following documentation for this: https://www.paraview.org/Wiki/CDash:API - So I got a hash-like string which should be my API token, right? The documentation is unfortunately not clear enough about how to use this token.

What I have been trying to do is this : I'm trying to access the URL https://\<cdash host name\>/api/v1/index.php?project=\<project name\>. I tried to pass a key-value pair (I have tried 'key:\<token\>' and 'Key:\<token\>') as a parameter in the URL query string; as a header of the HTTP request; as a form-encoded dictionary in the request body; and finally as a json-encoded dictionary in the request body. None of this seems to work, I keep getting a 401 code with the text '{"requirelogin":1}'

So what am I missing? In addition to the page that allows to generate API tokens, the documentation also mentions a 'login' method, which takes an API key as input and returns... another kind of API key ? I don't really understand the purpose of this auxiliary key, but I tried to use it (as a stab in the dark). I got the following results :

* Pass key:\<token\> in the URL query string: I get "incorrect API key passed"
* Pass is as header or body: I get "You must specify an API key"

Can you please tell me what is the proper way to use my API key to read https://\<cdash host name\>/api/v1/index.php?project=\<project name\>, and/or update the wiki with a detailed example?

**Comment by zackgalbreath** [comment]
Sounds like you got pretty close. You'll need to present your API token as a bearer token in the HTTP header.  Let us know if this Python snippet doesn't work for you.

```python
#!/usr/bin/env python

import requests

if __name__ == "__main__":
    headers = {"Authorization": "Bearer <your token here>"}
    url = "https://<cdash host name>/api/v1/index.php?project=<project name>"
    r = requests.get(url, headers=headers)
    if not r.ok:
      print("Error: {0} / {1}\n".format(r.status_code, r.text))
    else:
      print r.json()
```

**Comment by graslany** [comment]
Thanks for your answer, everything's working now :-)
