### ISSUE TITLE
Cannot migrate from 2.0.2 to 2.6.0: permission issues for administration

### ISSUE THREAD

**Issue by fspindle** [Kitware/CDash#866]
I have a database named `cdash` working with CDash 2.0.2.

In order to migrate to CDash 2.6.0,
- the database was dumped in `cdash_v2`
- CDash 2.6.0 was installed from zip
- in `config.local.php` I set `$CDASH_DB_NAME = 'cdash_v2'`

I'm able to connect to the CDash web server but once I select `Administration/Maintenance` I get the error message `You cannot access this page`.

When I try to create a dummy project, after pressing `Create project` button I get `Error: Permission denied` 

In the database `cdash_v2` I can see that the admin flag associated to my email is set to 1. This is also confirmed when I connect to the web server with the `Administration` items that I can see.  

Any hint would be appreciated

**Comment by zackgalbreath** [comment]
Hmm, not sure what might be going wrong here. If you start with a new database, does CDash v2.6.0 install cleanly on your system?

**Comment by kaikai2** [comment]
I had the same issue. 

It seems I cannot login as admin with the old database connected. I ended up modify /var/www/cdash/public/upgrade.php to comment out the line: checkUserPolicy to bypass the auth. After that, I can see upgrade buttons on the page and was able to upgrade the database. 

After database upgraded, I can logon with my credentials without problem. Hope this helps.

**Comment by fspindle** [comment]
Thanks for your feedback.
We finally succeed to install 2.6.0 with a new database.
