### ISSUE TITLE
Cannot register a new user

### ISSUE THREAD

**Issue by ugultopu** [Kitware/CDash#907]
Using `a92dc52`.

Installed CDash with docker:

```
sudo docker-compose pull cdash
sudo docker-compose up -d
sudo docker-compose run --rm cdash install configure
```

Went to `localhost:8080` and CDash is up:

![Screenshot from 2019-10-18 09-32-55](https://user-images.githubusercontent.com/9937444/67094702-b2429680-f18a-11e9-84d5-05ed2718fcf1.png)

Try to register a new user:

![Screenshot from 2019-10-18 09-35-11](https://user-images.githubusercontent.com/9937444/67094727-be2e5880-f18a-11e9-9073-fb10f254295d.png)

Getting a server error:

![Screenshot from 2019-10-18 09-34-12](https://user-images.githubusercontent.com/9937444/67094740-c4243980-f18a-11e9-8ffb-7fa45bac99af.png)

Is this expected or is this a bug? How can I get this working?

**Comment by williamjallen** [comment]
This feature definitely works on the latest version of master.  If you continue to experience this error after trying with the latest version of master, please open a new issue.
