### ISSUE TITLE
CDash stopped working after upgrading to php 7.3

### ISSUE THREAD

**Issue by ggael** [Kitware/CDash#911]
After upgrading my php version from 5.5 to 7.3, my CDash instance (version 2.4) stopped to work. I upgraded the CDash instance to the 2.6 version, but I still get similar issues:
 - the main page is mostly empty
 - if I directly request a project page I get the following error:

    Fatal error: Uncaught Error: Call to a member function quote() on bool in /mnt/www/html/CDash2/include/pdo.php:339 Stack trace: #0 /mnt/www/html/CDash2/include/pdo.php(360): pdo_real_escape_string('', NULL) #1 /mnt/www/html/CDash2/public/ajax/getfeed.php(26): pdo_real_escape_numeric('') #2 {main} thrown in /mnt/www/html/CDash2/include/pdo.php on line 339

My CDash instance is public, so you can see its full output by yourself: http://manao.inria.fr/CDash/index.php?project=Eigen

**Comment by williamjallen** [comment]
This issue is relatively old at this point and relates to a release of CDash which is no longer maintained.  Closing this now as part of a wider cleanup of stale issues.
