### ISSUE TITLE
Warning: Maximum number of builds reached for <project>. Contact webmaster@cdash.org for support.

### ISSUE THREAD

**Issue by matthiasdiener** [Kitware/CDash#921]
The Charm++ project on my.cdash.org (https://my.cdash.org/index.php?project=Charm%2B%2B) is hitting the build number limit:

> Warning: Maximum number of builds reached for Charm++. Contact webmaster@cdash.org for support.

New builds are not showing up anymore on the dashboard. I contacted webmaster@cdash.org but did not get a response.

**Comment by matthiasdiener** [comment]
Hi @zackgalbreath , any chance you could take a look at that? Thanks!

**Comment by zackgalbreath** [comment]
I increased the number of builds you're allowed for your project. Thanks for using CDash.

**Comment by matthiasdiener** [comment]
Thank you! 

Is there a way to automatically have old builds removed? I played around with the 
`AutoRemove Timeframe (days)` and `AutoRemove Max Builds` options, but could not get them to actually remove a build.
