### ISSUE TITLE
upgrade database fails to display dashboards

### ISSUE THREAD

**Issue by martin-resnick** [Kitware/CDash#972]
Was running cdash 2.2.0. Upgraded web code to "prebuilt".  Clicked "Upgrade CDash". Database schema went to 2.6 then Upgrade again and found it kept asking to upgrade. Saw your response to:
UPDATE version SET minor = 4;
Updated again and now all projects are listed. BUT when I click into a project it gives the feed but no build name rows.
I can get to buildSummary and drill down...just no rows of build names.

**Comment by williamjallen** [comment]
CDash 2.x is no longer supported.
