### ISSUE TITLE
Help install CDash

### ISSUE THREAD

**Issue by LLlKuIIeP** [Kitware/CDash#980]
Good time of day.

Please help me install CDash, follow the steps of the manual and still in the log file 'script / home / user / CDash / public / viewProjects.php not found or unable to stat'.

Thanks.

**Comment by zackgalbreath** [comment]
Hi, thanks for giving it a shot! I'm not 100% sure what's causing your problem, but here's a couple ideas.

* Filesystem permissions. Maybe your web user can't read files in that directory?
* mod_rewrite disabled on your web server. Our new Laravel router needs this turned on.

**Comment by LLlKuIIeP** [comment]
Good afternoon.
Installed through Docker, it turned out.
And you can find out, it doesn’t quite work out. Should TestConfig be next to the root CMakeLists file, should CTestCustom be in the build folder? Which team is running?

**Comment by zackgalbreath** [comment]
> Good afternoon.
> Installed through Docker, it turned out.
> And you can find out, it doesn’t quite work out. Should TestConfig be next to the root CMakeLists file, should CTestCustom be in the build folder? Which team is running?

That's right!

CTestConfig.cmake should be in the root of your source folder (next to CMakeLists.txt).

The default location for CTestCustom.cmake is the root of your build folder. If necessary you can copy it there using `file(COPY)` or `configure_file()`.

You can also change the location where ctest looks for CTestCustom.cmake by passing the location to  [`ctest_read_custom_files()`](https://cmake.org/cmake/help/latest/command/ctest_read_custom_files.html).

**Comment by emmenlau** [comment]
@LLlKuIIeP is this issue fixed for you?

**Comment by LLlKuIIeP** [comment]
Yes, thanks.
